import React, { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Lang = "ru" | "en";

export const translations = {
  ru: {
    // Header
    schedule: "Управление расписанием",
    logout: "Выйти",
    loggedPin: "Вход через PIN",
    loggedFid: "Вход через",
    // CRM tabs
    tabBookings: "Заявки",
    tabEmployees: "Сотрудники",
    tabArchive: "Архив",
    tabBlacklist: "Чёрный список",
    // Mobile sub-tabs
    slotsTab: "📅 Слоты",
    // Statuses
    statusPending: "⏳ Ожидает",
    statusApproved: "✅ Подтверждён",
    statusCompleted: "✓ Завершён",
    statusCancelled: "❌ Отменён",
    // Date selector panel
    selectDate: "Выберите дату",
    refresh: "Обновить",
    dateLabel: "Дата:",
    slotsFor: "Слоты на",
    slotFreeLabel: "🟢 Свободен",
    slotBlockedLabel: "🟠 Заблок.",
    slotTakenLabel: "🔴 Занят",
    blockReasonLabel: "Причина блокировки:",
    blockReasonPlaceholder: "Повторный вызов...",
    slotBlocked: "🔒 Заблокирован",
    slotFreeBtn: "Освободить",
    slotUnblock: "Разблокировать",
    slotBlockBtn: "Блок",
    slotBookBtn: "Бронь",
    slotApproved: "✅ Подтверждён",
    slotWaiting: "⏳ Ожидает",
    // Orders panel header
    allOrders: "Все заявки",
    activeOrders: "Активные заявки",
    activeTab: "Активные",
    searchPlaceholder: "Поиск по имени, телефону, адресу, дате (ГГГГ-ММ-ДД), технике…",
    clearSearch: "Очистить",
    found: "Найдено:",
    of: "из",
    selectAll: "Выбрать всё",
    deselectAll: "Снять всё",
    selected: "Выбрано:",
    deleteSelected: "Удалить выбранные",
    deselect: "× Сбросить",
    historyLabel: "История",
    errorLoadTitle: "Ошибка загрузки заявок",
    nothingFound: "Ничего не найдено — попробуйте другой запрос",
    noOrders: "Заявок пока нет",
    // Card/table fields
    createdLabel: "Создано:",
    // Desktop table headers
    thCreated: "Создано",
    thVisitDate: "Дата визита",
    thTime: "Время",
    thClient: "Клиент",
    thPhone: "Телефон",
    thAppliance: "Техника",
    thStatus: "Статус",
    thAction: "Действие",
    // Action buttons
    approveBtn: "Одобрить",
    editBtn: "Изменить",
    completeBtn: "Завершить",
    rescheduleBtn: "Перенести",
    cancelBtn: "Отменить",
    deletePerm: "Удалить навсегда",
    restoreBtn2: "Восстановить",
    recallBtn: "Повторный вызов",
    recallConfirm: "Вернуть заказ технику как повторный вызов?",
    clientSigned: "Клиент подписал",
    deleteBtn: "Удалить",
    // Action button titles
    titleApprove: "Одобрить бронирование и отправить email клиенту",
    titleEdit: "Изменить данные бронирования",
    titleReschedule: "Перенести на другую дату/время",
    titleComplete: "Отметить как выполнено (после фактического ремонта)",
    titleCancel: "Отменить бронирование",
    titleDelete: "Удалить заявку навсегда из базы данных",
    titleRestore: "Восстановить заявку в активные",
    // Bulk delete modal
    deleteBulkTitle: "Удалить выбранные заявки?",
    deleteBulkIrreversible: "⚠️ Действие необратимо. Все выбранные заявки будут удалены из базы данных навсегда.",
    deleting: "Удаляем...",
    deleteBulkBtn: "🗑️ Удалить",
    // Delete modal
    deletePermTitle: "Удалить заявку навсегда?",
    deletePermWarn: "⚠️ Это действие необратимо. Заявка будет удалена из базы данных без возможности восстановления.",
    deletePermBtn: "🗑️ Удалить навсегда",
    clientLabel: "Клиент:",
    // Restore modal
    restoreTitle: "Восстановить заявку?",
    dateShort: "Дата:",
    showEdits: "✏️ Внести изменения в заявку",
    hideEdits: "Скрыть изменения",
    restoreNote: "Заявка вернётся в раздел активных со статусом «Ожидает». HubSpot-сделка будет создана заново.",
    restoring: "⏳ Восстанавливаем...",
    restoreActionBtn: "♻️ Восстановить",
    // Restore edit fields
    fieldName: "Имя клиента",
    fieldPhone: "Телефон",
    fieldEmail: "Email",
    fieldAddress: "Адрес",
    fieldAppliance: "Техника",
    fieldIssue: "Описание поломки",
    fieldNewDate: "Новая дата",
    fieldNewTime: "Новое время",
    // Conflict modal
    conflictTitle: "Конфликт расписания!",
    conflictTaken: "Это время уже занято:",
    conflictPickOther: "Выберите другую дату и время для заявки",
    // Edit booking modal
    editBookingTitle: "Изменить бронирование",
    labelStatus: "Статус:",
    clientLangLabel: "Язык клиента:",
    clientLangEn: "Английский",
    clientLangEs: "Испанский",
    clientNameReq: "Имя клиента *",
    phoneReq: "Телефон *",
    emailClient: "Email клиента",
    addressOptional: "Адрес (необязательно)",
    applianceOptional: "Техника (необязательно)",
    dateReq: "Дата *",
    dateFormatHint: "Формат: Apr 25, 2026",
    timeReq: "Время *",
    noteOptional: "Заметка (необязательно)",
    notePlaceholder: "Дополнительная информация…",
    saveEdits: "Сохранить изменения",
    savingDots: "Сохранение…",
    // Manual booking modal
    createBookingTitle: "Создать бронирование",
    zipOptional: "ZIP-код (необязательно)",
    appliancePlaceholderRu: "Холодильник, стиральная машина...",
    addlInfoPlaceholder: "Доп. информация...",
    bookBtn: "Забронировать",
    savingBook: "Сохраняю…",
    // Complete modal
    completeTitle: "Завершить заявку?",
    completeDesc: "Завершение переместит заявку в историю. Это нельзя отменить автоматически.",
    completePaySection: "Оплата (необязательно)",
    completeMethodLabel: "Метод оплаты",
    completeMethodPlaceholder: "Нал, Безнал, Карта...",
    completeAmountLabel: "Сумма ($)",
    completeBtnLabel: "✓ Завершить",
    // Cancel modal
    cancelTitle: "Отменить бронирование?",
    cancelSlotWill: "Слот будет освобождён:",
    cancelBtnLabel: "Отменить бронирование",
    // Employees
    empTitle: "Сотрудники",
    empAddBtn: "Добавить сотрудника",
    empName: "Имя",
    empPhone: "Телефон",
    empCar: "Авто",
    empPlate: "Госномер",
    empActions: "Действия",
    empEdit: "Редактировать",
    empWarnings: "Замечания",
    empFire: "Уволить",
    empFireConfirm: "Уволить сотрудника?",
    empFireMsg: "Сотрудник будет перемещён в архив уволенных. Его заказы сохранятся в истории.",
    empFireYes: "Да, уволить",
    sectionBank: "Банк / Bank",
    sectionVehicle: "Авто / Vehicle",
    empBankName: "Название банка",
    empBankAccount: "Счёт",
    empBankRouting: "Routing",
    empAddress: "Адрес",
    empCarMake: "Марка",
    empCarModel: "Модель",
    empPin: "PIN (мин. 4 цифры)",
    empPinNew: "Новый PIN (оставьте пустым чтобы не менять)",
    empSave: "Сохранить",
    empCancel: "Отмена",
    empAdd: "Добавить",
    empNoActive: "Нет активных сотрудников",
    empLang: "Язык интерфейса",
    // Warnings
    warnTitle: "Замечания",
    warnNone: "Замечаний нет",
    warnAdd: "+ Добавить замечание",
    warnText: "Текст замечания",
    warnSeverity: "Степень серьёзности",
    warnLow: "🟡 Низкая",
    warnMedium: "🟠 Средняя",
    warnHigh: "🔴 Высокая",
    warnDelete: "Удалить",
    warnDeleteConfirm: "Удалить замечание?",
    warnDeleteYes: "Удалить",
    warnAdded: "Замечание добавлено",
    // Archive
    archTitle: "Уволенные сотрудники",
    archName: "Имя",
    archFiredAt: "Дата увольнения",
    archNoFired: "Нет уволенных сотрудников",
    archViewProfile: "Профиль",
    archHistory: "История заказов",
    archNoHistory: "Заказов нет",
    archReadOnly: "Профиль (только чтение)",
    archWarnings: "Замечания (история)",
    // Blacklist
    blTitle: "Чёрный список клиентов",
    blAdd: "Добавить клиента",
    blName: "Имя клиента",
    blPhone: "Телефон",
    blAddress: "Адрес",
    blReason: "Причина",
    blNotes: "Заметки",
    blDate: "Дата добавления",
    blEdit: "Изменить",
    blDelete: "Удалить",
    blDeleteConfirm: "Удалить из чёрного списка?",
    blDeleteYes: "Да, удалить",
    blSearch: "Поиск по имени, телефону, адресу...",
    blNoResults: "Список пуст",
    blSave: "Сохранить",
    blCancel: "Отмена",
    blEmpty: "Не указано",
    // CRM: assignment / payment
    assignEmployee: "Назначить сотрудника",
    filterEmployee: "Фильтр по сотруднику",
    filterCategory: "Категория",
    tabPhotos: "Фото",
    pay: "Оплата",
    photoUploadTitle: "Загрузка фото",
    photoUploadDesc: "Фото для галереи сайта",
    filterAll: "Все",
    filterAppliance: "Appliance",
    filterDental: "Dental",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    remoteBookingHint: "Только просмотр — заявка с другого сайта",
    allEmployees: "Все сотрудники",
    notAssigned: "Не назначен",
    payMethod: "Оплата",
    payAmount: "Сумма",
    assigned: "Назначен",
    // Error messages
    errFillRequired: "Заполните обязательные поля: имя, телефон, дата, время",
    errSlotTaken: "Этот слот уже занят. Выберите другое время.",
    errNetwork: "Ошибка сети",
    errServer: "Ошибка сервера",
    errNamePhoneRequired: "Имя и телефон обязательны",
    errPinTooShort: "PIN минимум 8 символов",
    errEnterNamePhone: "Введите имя и телефон",
    errSlotTakenShort: "Этот слот уже занят",
    errNoConnection: "Нет соединения с сервером. Проверьте сеть или задеплойте бэкенд.",
    // General
    back: "Назад",
    confirm: "Подтвердить",
    loading: "Загрузка...",
    error: "Ошибка",
    save: "Сохранить",
    close: "Закрыть",
    search: "Поиск",
    date: "Дата",
    status: "Статус",
    noData: "Нет данных",
    cancel: "Отмена",
    // loadSchedule errors
    errScheduleStatus: "Сервер вернул ошибку ",
    errCheckPin: "Проверьте PIN и попробуйте снова.",
    errScheduleInvalid: "API вернул неверный ответ. Возможно, вы используете устаревшую версию сайта. Откройте панель администратора через правильный URL.",
    errConnectionPrefix: "Ошибка подключения к серверу: ",
    // Face ID section
    fidSectionTitle: "Зарегистрированные устройства Face ID",
    fidRefreshBtn: "Обновить",
    fidTryAgain: "Попробовать снова",
    fidLoading: "Загрузка…",
    fidEmpty: "Face ID устройства не зарегистрированы.",
    fidAt: "в",
    fidDevice: "Устройство",
    fidRenamed: "Переименовано",
    fidRenameBtn: "Переименовать",
    fidCancelBtn: "Отмена",
    fidDevicePlaceholder: "Название устройства",
    fidSaving: "Сохранение…",
    fidSave: "Сохранить",
    fidRemoveBtn: "Удалить",
    fidRemoveTitle: "Удалить устройство Face ID?",
    fidRemoveDevice: "Устройство:",
    fidRemoveInfo: "После удаления это устройство потребует повторной регистрации Face ID или входа по паролю для доступа в панель.",
    fidRemoving: "Удаление…",
    fidRemoveYes: "Да, удалить",
    fidRegisteredToast: "Face ID зарегистрирован",
    fidDeviceAddedToast: "Новое устройство успешно добавлено.",
    // Payment status
    payStatus: "Статус оплаты",
    payStatusPaid: "✅ Оплачено",
    payStatusUnpaid: "❌ Не оплачено",
    payStatusPending: "⏳ Ожидает оплаты",
    payStatusCash: "💵 Кэш",
    resendPaymentBtn: "Отправить ссылку повторно",
    resendPaymentSending: "Отправка...",
    resendPaymentSent: "✅ Отправлено",
    downloadReceiptBtn: "Скачать чек (PDF)",
    downloadReceiptDownloading: "Создание PDF…",
    downloadReceiptError: "Не удалось создать чек. Попробуйте ещё раз.",
    resendReceiptBtn: "Отправить чек повторно",
    resendReceiptSending: "Отправка…",
    resendReceiptSent: "✅ Чек отправлен",
    resendReceiptError: "Не удалось отправить чек. Попробуйте ещё раз.",
    estimateBtn: "Смета",
    estimateTitle: "Создать смету для клиента",
    estimateItems: "Позиции",
    addItem: "+ Добавить",
    itemDesc: "Описание",
    itemQty: "Кол-во",
    itemPrice: "Цена ($)",
    estimateNotes: "Заметки (необ.)",
    estimateNotesPlaceholder: "Заметки для клиента...",
    estimateSend: "Отправить клиенту",
    estimateSending: "Отправка...",
    estimateSuccess: "Смета отправлена!",
    estimateErr: "Ошибка отправки",
    estimateEditTitle: "Редактировать и отправить смету",
    estimateSentBadge: "Смета",
    estimateEditBtn: "Изм. / Повтор",
    noTax: "Без налога (скидка для клиента)",
    estimateSubtotal: "Итого",
    estimateTaxLine: "Налог (8.25%)",
    estimateTotalLine: "К оплате",
    receiptResentCount: (n: number) => `Отправлено повторно ${n} ${n === 1 ? "раз" : "раз(а)"}`,
    receiptLastResentAt: "последний раз",
    receiptHistoryToggleShow: "История скачиваний чека",
    receiptHistoryToggleHide: "Скрыть историю скачиваний",
    receiptHistoryLoading: "Загрузка истории…",
    receiptHistoryEmpty: "Пока никто не скачивал чек.",
    receiptHistoryError: "Не удалось загрузить историю скачиваний.",
    receiptHistoryActorAdmin: "Админ",
    receiptHistoryActorEmployee: "Сотрудник",
    receiptHistoryActorClient: "Клиент",
    receiptHistoryActorUnknown: "Неизвестно",
    receiptHistoryIp: "IP",
    receiptHistoryLocation: "местоположение",
    receiptHistorySuspicious: "Подозрительно",
    receiptHistoryLang: "язык",
    receiptHistoryUserAgent: "Браузер",
    receiptHistoryFilterFrom: "С даты",
    receiptHistoryFilterTo: "По дату",
    receiptHistoryFilterActor: "Кто скачал",
    receiptHistoryFilterActorAll: "Все",
    receiptHistoryExportCsv: "Экспорт CSV",
    receiptHistoryExportError: "Не удалось скачать CSV.",
    receiptHistoryFilterSearch: "Поиск",
    receiptHistoryFilterSearchPlaceholder: "IP, имя или браузер",
    tabTrash: "Корзина",
    trashTitle: "Корзина",
    trashEmpty: "Корзина пуста",
    trashCount: (n: number) => `${n} ${n === 1 ? "запись" : n < 5 ? "записи" : "записей"}`,
    trashDeletedAt: "Удалено:",
    trashRestoreBtn: "Восстановить",
    trashRestoring: "Восстановление…",
    trashPermanentBtn: "Удалить навсегда",
    trashDeleting: "Удаление…",
    trashEmptyBtn: "Очистить корзину",
    trashEmptyConfirmTitle: "Очистить корзину?",
    trashEmptyConfirmMsg: "⚠️ Все заявки в корзине будут удалены НАВСЕГДА. Это действие необратимо.",
    trashEmptyConfirmYes: "🗑️ Да, очистить",
    trashEmptying: "Очистка…",
    trashPermanentConfirmTitle: "Удалить навсегда?",
    trashPermanentConfirmMsg: "⚠️ Заявка будет удалена из базы данных без возможности восстановления.",
    trashPermanentConfirmYes: "🗑️ Удалить навсегда",
    trashRestoredToast: "Заявка восстановлена",
    trashNote: "Заявки в корзине автоматически не удаляются. Удалите вручную, когда они больше не нужны.",
    moveToTrashBtn: "В корзину",
    moveToTrashTitle: "Переместить заявку в корзину",
    moveToTrashBulkTitle: "Переместить выбранные в корзину",
    moveToTrashBulkMsg: "Выбранные заявки будут перемещены в корзину. Их можно будет восстановить.",
    moveToTrashBulkBtn: "🗑️ В корзину",
    moveToTrashSingleTitle: "Переместить в корзину?",
    moveToTrashSingleMsg: "Заявку можно будет восстановить из корзины.",
    moveToTrashSingleBtn: "🗑️ В корзину",
    tabReports: "Отчёты",
    tabPricebook: "Прайс-лист",
    tabSettings: "Настройки",
    // CRM Payroll tab
    tabPayroll: "Зарплата",
    payrollPeriod: "Период",
    payrollEmployee: "Сотрудник",
    payrollJobs: "Заказов",
    payrollGross: "Начислено",
    payrollDeductions: "Вычеты",
    payrollNet: "К выплате",
    payrollStatus: "Статус",
    payrollNotes: "Заметки",
    payrollStatusPaid: "✅ Выплачено",
    payrollStatusPending: "⏳ Ожидает",
    payrollStatusCancelled: "❌ Отменено",
    payrollCalculate: "Рассчитать зарплату",
    payrollNoRecords: "Записей о зарплате нет",
    payrollPeriodStart: "Начало периода",
    payrollPeriodEnd: "Конец периода",
    payrollCommissionPct: "Комиссия (%)",
    payrollFlatRate: "Фикс. ставка ($)",
    payrollDeductionsInput: "Вычеты ($)",
    payrollPeriodLabel: "Название периода",
    payrollSubmit: "Рассчитать",
    payrollMarkPaid: "Отметить оплаченной",
    payrollDelete: "Удалить",
    payrollAll: "Все сотрудники",
    // Stripe payment
    stripePayLink: "💳 Ссылка оплаты",
    stripeGenLink: "Создать ссылку",
    stripeSendLink: "Ссылка создана",
    stripeAmount: "Сумма ($)",
    stripeDesc: "Описание",
    stripeCopied: "Скопировано!",
    stripeNoKey: "Stripe не настроен (нет STRIPE_SECRET_KEY)",
    stripeAlreadyPaid: "✅ Оплачено через Stripe",
    stripeGenerating: "Создание...",
    // Weekly Summary
    weeklyTabLabel: "Неделя",
    weeklySummaryTitle: "Итог недели",
    weeklyPeriod: "Период",
    weeklyEmployee: "Сотрудник",
    weeklyJobs: "Заказов",
    weeklyLabor: "Работа",
    weeklyParts: "Запчасти",
    weeklyTax: "Налог (8.25%)",
    weeklyNet: "К выплате",
    weeklyTotal: "ИТОГО",
    weeklyLoading: "Загрузка...",
    weeklyNoData: "Нет данных за текущую неделю",
    // Call Logs
    callLogsTitle: "Журнал звонков",
    callLogsFrom: "С даты",
    callLogsTo: "По дату",
    callLogsStatus: "Статус",
    callLogsStatusAll: "Все",
    callLogsStatusCompleted: "Заявка создана",
    callLogsStatusNoBooking: "Клиент завершил звонок",
    callLogsStatusError: "Ошибка",
    callLogsApply: "Применить",
    callLogsExportCsv: "Экспорт CSV",
    callLogsThWhen: "Дата/время",
    callLogsThPhone: "Телефон",
    callLogsThStatus: "Статус",
    callLogsThDuration: "Длит. (сек)",
    callLogsThBooking: "Заявка",
    callLogsOpenBooking: "Открыть",
    callLogsEmpty: "Звонков не найдено",
    callLogsError: "Ошибка загрузки журнала звонков",
    callLogsTranscriptTitle: "Транскрипт разговора",
    callLogsTranscriptEmpty: "Транскрипт недоступен",
    callLogsTranscriptAgent: "Агент",
    callLogsTranscriptCustomer: "Клиент",
    callLogsRecording: "Запись звонка",
    callLogsRecordingUnsupported: "Ваш браузер не поддерживает воспроизведение аудио.",
    callLogsCallBack: "Перезвонить",
    callLogsCallingBack: "Звоним…",
    callLogsCallBackOk: "Телефон сейчас позвонит",
    callLogsCallBackErr: "Не удалось инициировать звонок",
    callLogsCount: (n: number) => `${n} звонк${n === 1 ? "" : n < 5 ? "а" : "ов"}`,
    callLogsDelete: "Удалить",
    callLogsDeleteConfirm: "Удалить запись о звонке?",
    callLogsDeleteOk: "Запись удалена",
    callLogsDeleteErr: "Не удалось удалить",
    callLogsDeletedAt: "Удалён",
    callLogsRestore: "Восстановить",
    callLogsRestoreOk: "Запись восстановлена",
    callLogsRestoreErr: "Не удалось восстановить",
    callLogsRestoreExpired: "Срок восстановления истёк (90 дней)",
    callLogsShowDeleted: "Показать удалённые",
    callLogsHideDeleted: "Скрыть удалённые",
    // Downloads section (global receipt downloads in Reports tab)
    downloadsTabLabel: "Скачивания",
    downloadsTitle: "Скачивания чеков (все заявки)",
    downloadsFilterBookingId: "ID заявки",
    downloadsFilterBookingPlaceholder: "необязательно",
    downloadsApplyFilters: "Применить",
    downloadsSuspiciousOnly: "⚠ Только подозрительные",
    downloadsExporting: "Экспорт…",
    downloadsEmpty: "Нет скачиваний, соответствующих фильтрам.",
    downloadsThWhen: "Когда",
    downloadsThClient: "Клиент / Заявка",
    downloadsThActor: "Кто",
    downloadsThIpLocation: "IP / Местоположение",
    downloadsThBrowser: "Браузер",
    downloadsNoSuspicious: "Подозрительных скачиваний не найдено.",
    downloadsSuspiciousBadge: "⚠ Подозрительно",
    downloadsCount: (n: number) => `${n} скачивани${n === 1 ? "е" : n < 5 ? "я" : "й"}`,
    downloadsSuspiciousCount: (n: number) => `⚠ ${n} подозрительн${n === 1 ? "ое" : n < 5 ? "ых" : "ых"}`,
    downloadsOf: "из",
    downloadsTotal: "всего",
    downloadsErrorLoad: "Ошибка загрузки скачиваний",
    downloadsErrorConnection: "Ошибка подключения",
    downloadsErrorExport: "Не удалось скачать CSV",
    // Booking-level calls section
    bookingCallsToggleShow: "📞 Показать звонки",
    bookingCallsToggleHide: "📞 Скрыть звонки",
    bookingCallsEmpty: "Звонков по этой заявке нет",
    bookingCallsLoading: "Загрузка звонков…",
    bookingCallsOpenTranscript: "Транскрипт",
    callLogsShowing: (shown: number, total: number) => `Показано ${shown} из ${total}`,
    callLogsPrev: "Предыдущая",
    callLogsNext: "Следующая",
    callLogsPage: (page: number, total: number) => `Стр. ${page} / ${total}`,
    photosShow: "📷 Фото и подпись",
    photosHide: "📷 Скрыть фото",
    photosEmpty: "Нет фото",
    sigNone: "Нет подписи",
    sigTitle: "Подпись клиента",
    cabinetBtn: "Кабинет",
    cabinetTitle: "Кабинет сотрудника",
    cabinetNoBookings: "Нет назначенных заказов",
    cabinetCloseJob: "Закрыть заказ",
    cabinetCloseTitle: "Закрыть заказ (admin)",
    cabinetBookingsLabel: "Заказы",
    // date locale
    dateLocale: "ru-RU",
  },
  en: {
    // Header
    schedule: "Schedule Management",
    logout: "Logout",
    loggedPin: "Logged in via PIN",
    loggedFid: "Logged in with",
    // CRM tabs
    tabBookings: "Orders",
    tabEmployees: "Employees",
    tabArchive: "Archive",
    tabBlacklist: "Blacklist",
    // Mobile sub-tabs
    slotsTab: "📅 Slots",
    // Statuses
    statusPending: "⏳ Pending",
    statusApproved: "✅ Confirmed",
    statusCompleted: "✓ Completed",
    statusCancelled: "❌ Cancelled",
    // Date selector panel
    selectDate: "Select Date",
    refresh: "Refresh",
    dateLabel: "Date:",
    slotsFor: "Slots for",
    slotFreeLabel: "🟢 Free",
    slotBlockedLabel: "🟠 Blocked",
    slotTakenLabel: "🔴 Taken",
    blockReasonLabel: "Block reason:",
    blockReasonPlaceholder: "Repeat visit...",
    slotBlocked: "🔒 Blocked",
    slotFreeBtn: "Free",
    slotUnblock: "Unblock",
    slotBlockBtn: "Block",
    slotBookBtn: "Book",
    slotApproved: "✅ Confirmed",
    slotWaiting: "⏳ Pending",
    // Orders panel header
    allOrders: "All Orders",
    activeOrders: "Active Orders",
    activeTab: "Active",
    searchPlaceholder: "Search by name, phone, address, date (YYYY-MM-DD), appliance…",
    clearSearch: "Clear",
    found: "Found:",
    of: "of",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    selected: "Selected:",
    deleteSelected: "Delete selected",
    deselect: "× Reset",
    historyLabel: "History",
    errorLoadTitle: "Error loading orders",
    nothingFound: "Nothing found — try a different query",
    noOrders: "No orders yet",
    // Card/table fields
    createdLabel: "Created:",
    // Desktop table headers
    thCreated: "Created",
    thVisitDate: "Visit Date",
    thTime: "Time",
    thClient: "Client",
    thPhone: "Phone",
    thAppliance: "Appliance",
    thStatus: "Status",
    thAction: "Action",
    // Action buttons
    approveBtn: "Approve",
    editBtn: "Edit",
    completeBtn: "Complete",
    rescheduleBtn: "Reschedule",
    cancelBtn: "Cancel",
    deletePerm: "Delete permanently",
    restoreBtn2: "Restore",
    recallBtn: "Recall",
    recallConfirm: "Return this job to the technician as a recall?",
    clientSigned: "Client signed",
    deleteBtn: "Delete",
    // Action button titles
    titleApprove: "Approve booking and send email to client",
    titleEdit: "Edit booking details",
    titleReschedule: "Reschedule to another date/time",
    titleComplete: "Mark as done (after actual repair)",
    titleCancel: "Cancel booking",
    titleDelete: "Permanently delete order from database",
    titleRestore: "Restore to active orders",
    // Bulk delete modal
    deleteBulkTitle: "Delete selected orders?",
    deleteBulkIrreversible: "⚠️ Irreversible action. All selected orders will be permanently deleted from the database.",
    deleting: "Deleting...",
    deleteBulkBtn: "🗑️ Delete",
    // Delete modal
    deletePermTitle: "Delete order permanently?",
    deletePermWarn: "⚠️ This action is irreversible. The order will be deleted from the database with no way to recover it.",
    deletePermBtn: "🗑️ Delete permanently",
    clientLabel: "Client:",
    // Restore modal
    restoreTitle: "Restore order?",
    dateShort: "Date:",
    showEdits: "✏️ Edit order before restoring",
    hideEdits: "Hide edits",
    restoreNote: "Order will return to active with Pending status. A new HubSpot deal will be created.",
    restoring: "⏳ Restoring...",
    restoreActionBtn: "♻️ Restore",
    // Restore edit fields
    fieldName: "Client Name",
    fieldPhone: "Phone",
    fieldEmail: "Email",
    fieldAddress: "Address",
    fieldAppliance: "Appliance",
    fieldIssue: "Issue description",
    fieldNewDate: "New Date",
    fieldNewTime: "New Time",
    // Conflict modal
    conflictTitle: "Schedule conflict!",
    conflictTaken: "This time is already taken:",
    conflictPickOther: "Please select a new date and time for",
    // Edit booking modal
    editBookingTitle: "Edit Booking",
    labelStatus: "Status:",
    clientLangLabel: "Client Language:",
    clientLangEn: "English",
    clientLangEs: "Spanish",
    clientNameReq: "Client Name *",
    phoneReq: "Phone *",
    emailClient: "Client Email",
    addressOptional: "Address (optional)",
    applianceOptional: "Appliance (optional)",
    dateReq: "Date *",
    dateFormatHint: "Format: Apr 25, 2026",
    timeReq: "Time *",
    noteOptional: "Note (optional)",
    notePlaceholder: "Additional info…",
    saveEdits: "Save changes",
    savingDots: "Saving…",
    // Manual booking modal
    createBookingTitle: "Create Booking",
    zipOptional: "ZIP code (optional)",
    appliancePlaceholderRu: "Refrigerator, washer, dryer...",
    addlInfoPlaceholder: "Additional info...",
    bookBtn: "Book",
    savingBook: "Saving…",
    // Complete modal
    completeTitle: "Complete order?",
    completeDesc: "Completing will move the order to history. This cannot be auto-undone.",
    completePaySection: "Payment (optional)",
    completeMethodLabel: "Payment method",
    completeMethodPlaceholder: "Cash, Card, Online...",
    completeAmountLabel: "Amount ($)",
    completeBtnLabel: "✓ Complete",
    // Cancel modal
    cancelTitle: "Cancel booking?",
    cancelSlotWill: "Slot will be freed:",
    cancelBtnLabel: "Cancel booking",
    // Employees
    empTitle: "Employees",
    empAddBtn: "Add Employee",
    empName: "Name",
    empPhone: "Phone",
    empCar: "Vehicle",
    empPlate: "Plate",
    empActions: "Actions",
    empEdit: "Edit",
    empWarnings: "Warnings",
    empFire: "Fire",
    empFireConfirm: "Fire this employee?",
    empFireMsg: "The employee will be moved to the archive. Their job history will be preserved.",
    empFireYes: "Yes, fire",
    sectionBank: "Bank",
    sectionVehicle: "Vehicle",
    empBankName: "Bank Name",
    empBankAccount: "Account #",
    empBankRouting: "Routing #",
    empAddress: "Address",
    empCarMake: "Make",
    empCarModel: "Model",
    empPin: "PIN (min 4 digits)",
    empPinNew: "New PIN (leave blank to keep current)",
    empSave: "Save",
    empCancel: "Cancel",
    empAdd: "Add",
    empNoActive: "No active employees",
    empLang: "UI Language",
    warnTitle: "Warnings",
    warnNone: "No warnings on record",
    warnAdd: "+ Add Warning",
    warnText: "Warning description",
    warnSeverity: "Severity",
    warnLow: "🟡 Low",
    warnMedium: "🟠 Medium",
    warnHigh: "🔴 High",
    warnDelete: "Delete",
    warnDeleteConfirm: "Delete this warning?",
    warnDeleteYes: "Delete",
    warnAdded: "Warning added",
    archTitle: "Fired Employees",
    archName: "Name",
    archFiredAt: "Fired Date",
    archNoFired: "No fired employees",
    archViewProfile: "View Profile",
    archHistory: "Job History",
    archNoHistory: "No jobs",
    archReadOnly: "Profile (read only)",
    archWarnings: "Warnings (history)",
    blTitle: "Client Blacklist",
    blAdd: "Add Client",
    blName: "Client Name",
    blPhone: "Phone",
    blAddress: "Address",
    blReason: "Reason",
    blNotes: "Notes",
    blDate: "Date Added",
    blEdit: "Edit",
    blDelete: "Delete",
    blDeleteConfirm: "Remove from blacklist?",
    blDeleteYes: "Yes, delete",
    blSearch: "Search by name, phone, address...",
    blNoResults: "List is empty",
    blSave: "Save",
    blCancel: "Cancel",
    blEmpty: "Not specified",
    assignEmployee: "Assign Employee",
    filterEmployee: "Filter by Employee",
    filterCategory: "Category",
    tabPhotos: "Photos",
    pay: "Pay",
    photoUploadTitle: "Photo upload",
    photoUploadDesc: "Photos for site gallery",
    filterAll: "All",
    filterAppliance: "Appliance",
    filterDental: "Dental",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    remoteBookingHint: "View only — booking from the other site",
    allEmployees: "All Employees",
    notAssigned: "Unassigned",
    payMethod: "Payment",
    payAmount: "Amount",
    assigned: "Assigned",
    // Error messages
    errFillRequired: "Fill required fields: name, phone, date, time",
    errSlotTaken: "This slot is already taken. Choose another time.",
    errNetwork: "Network error",
    errServer: "Server error",
    errNamePhoneRequired: "Name and phone are required",
    errPinTooShort: "PIN must be at least 8 characters",
    errEnterNamePhone: "Enter name and phone",
    errSlotTakenShort: "Slot is already taken",
    errNoConnection: "No connection to server. Check network or deploy backend.",
    // General
    back: "Back",
    confirm: "Confirm",
    loading: "Loading...",
    error: "Error",
    save: "Save",
    close: "Close",
    search: "Search",
    date: "Date",
    status: "Status",
    noData: "No data",
    cancel: "Cancel",
    // loadSchedule errors
    errScheduleStatus: "Server returned error ",
    errCheckPin: "Check your PIN and try again.",
    errScheduleInvalid: "API returned invalid response. You may be using an outdated version of the site. Open the admin panel via the correct URL.",
    errConnectionPrefix: "Server connection error: ",
    // Face ID section
    fidSectionTitle: "Registered Face ID Devices",
    fidRefreshBtn: "Refresh",
    fidTryAgain: "Try again",
    fidLoading: "Loading…",
    fidEmpty: "No Face ID devices registered yet.",
    fidAt: "at",
    fidDevice: "Device",
    fidRenamed: "Renamed",
    fidRenameBtn: "Rename",
    fidCancelBtn: "Cancel",
    fidDevicePlaceholder: "Device name",
    fidSaving: "Saving…",
    fidSave: "Save",
    fidRemoveBtn: "Remove",
    fidRemoveTitle: "Remove Face ID Device?",
    fidRemoveDevice: "Device:",
    fidRemoveInfo: "After removal, this device will need to re-register with Face ID or use the password to access the admin panel.",
    fidRemoving: "Removing…",
    fidRemoveYes: "Yes, Remove",
    fidRegisteredToast: "Face ID registered",
    fidDeviceAddedToast: "New device added successfully.",
    // Payment status
    payStatus: "Payment Status",
    payStatusPaid: "✅ Paid",
    payStatusUnpaid: "❌ Unpaid",
    payStatusPending: "⏳ Awaiting Payment",
    payStatusCash: "💵 Cash",
    resendPaymentBtn: "Resend Payment Link",
    resendPaymentSending: "Sending...",
    resendPaymentSent: "✅ Sent",
    downloadReceiptBtn: "Download Receipt (PDF)",
    downloadReceiptDownloading: "Generating PDF…",
    downloadReceiptError: "Could not generate receipt. Please try again.",
    resendReceiptBtn: "Resend Receipt",
    resendReceiptSending: "Sending…",
    resendReceiptSent: "✅ Receipt sent",
    resendReceiptError: "Could not resend receipt. Please try again.",
    estimateBtn: "Estimate",
    estimateTitle: "Create Estimate for Client",
    estimateItems: "Line Items",
    addItem: "+ Add",
    itemDesc: "Description",
    itemQty: "Qty",
    itemPrice: "Price ($)",
    estimateNotes: "Notes (opt.)",
    estimateNotesPlaceholder: "Notes for the client...",
    estimateSend: "Send to Client",
    estimateSending: "Sending...",
    estimateSuccess: "Estimate sent!",
    estimateErr: "Send error",
    estimateEditTitle: "Edit & Resend Estimate",
    estimateSentBadge: "Estimate",
    estimateEditBtn: "Edit / Resend",
    noTax: "No tax (discount for client)",
    estimateSubtotal: "Subtotal",
    estimateTaxLine: "Tax (8.25%)",
    estimateTotalLine: "Total Due",
    receiptResentCount: (n: number) => `Resent ${n} time${n === 1 ? "" : "s"}`,
    receiptLastResentAt: "last sent",
    receiptHistoryToggleShow: "Receipt download history",
    receiptHistoryToggleHide: "Hide download history",
    receiptHistoryLoading: "Loading history…",
    receiptHistoryEmpty: "No one has downloaded this receipt yet.",
    receiptHistoryError: "Could not load download history.",
    receiptHistoryActorAdmin: "Admin",
    receiptHistoryActorEmployee: "Employee",
    receiptHistoryActorClient: "Client",
    receiptHistoryActorUnknown: "Unknown",
    receiptHistoryIp: "IP",
    receiptHistoryLocation: "location",
    receiptHistorySuspicious: "Suspicious",
    receiptHistoryLang: "lang",
    receiptHistoryUserAgent: "Browser",
    receiptHistoryFilterFrom: "From",
    receiptHistoryFilterTo: "To",
    receiptHistoryFilterActor: "Actor",
    receiptHistoryFilterActorAll: "All",
    receiptHistoryExportCsv: "Export CSV",
    receiptHistoryExportError: "Could not export CSV.",
    receiptHistoryFilterSearch: "Search",
    receiptHistoryFilterSearchPlaceholder: "IP, name, or browser",
    tabTrash: "Trash",
    trashTitle: "Trash",
    trashEmpty: "Trash is empty",
    trashCount: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
    trashDeletedAt: "Deleted:",
    trashRestoreBtn: "Restore",
    trashRestoring: "Restoring…",
    trashPermanentBtn: "Delete forever",
    trashDeleting: "Deleting…",
    trashEmptyBtn: "Empty trash",
    trashEmptyConfirmTitle: "Empty trash?",
    trashEmptyConfirmMsg: "⚠️ All bookings in trash will be permanently deleted. This cannot be undone.",
    trashEmptyConfirmYes: "🗑️ Yes, empty trash",
    trashEmptying: "Emptying…",
    trashPermanentConfirmTitle: "Delete permanently?",
    trashPermanentConfirmMsg: "⚠️ This booking will be permanently removed from the database.",
    trashPermanentConfirmYes: "🗑️ Delete permanently",
    trashRestoredToast: "Booking restored",
    trashNote: "Trashed bookings are not auto-deleted. Delete manually when no longer needed.",
    moveToTrashBtn: "Move to trash",
    moveToTrashTitle: "Move booking to trash",
    moveToTrashBulkTitle: "Move selected to trash",
    moveToTrashBulkMsg: "Selected bookings will be moved to trash. They can be restored later.",
    moveToTrashBulkBtn: "🗑️ Move to trash",
    moveToTrashSingleTitle: "Move to trash?",
    moveToTrashSingleMsg: "This booking can be restored from trash later.",
    moveToTrashSingleBtn: "🗑️ Move to trash",
    tabReports: "Reports",
    tabPricebook: "Price Book",
    tabSettings: "Settings",
    // CRM Payroll tab
    tabPayroll: "Payroll",
    payrollPeriod: "Period",
    payrollEmployee: "Employee",
    payrollJobs: "Jobs",
    payrollGross: "Gross",
    payrollDeductions: "Deductions",
    payrollNet: "Net Pay",
    payrollStatus: "Status",
    payrollNotes: "Notes",
    payrollStatusPaid: "✅ Paid",
    payrollStatusPending: "⏳ Pending",
    payrollStatusCancelled: "❌ Cancelled",
    payrollCalculate: "Calculate Payroll",
    payrollNoRecords: "No payroll records yet",
    payrollPeriodStart: "Period Start",
    payrollPeriodEnd: "Period End",
    payrollCommissionPct: "Commission (%)",
    payrollFlatRate: "Flat Rate ($)",
    payrollDeductionsInput: "Deductions ($)",
    payrollPeriodLabel: "Period Label",
    payrollSubmit: "Calculate",
    payrollMarkPaid: "Mark as Paid",
    payrollDelete: "Delete",
    payrollAll: "All Employees",
    // Stripe payment
    stripePayLink: "💳 Payment Link",
    stripeGenLink: "Generate Link",
    stripeSendLink: "Link Created",
    stripeAmount: "Amount ($)",
    stripeDesc: "Description",
    stripeCopied: "Copied!",
    stripeNoKey: "Stripe not configured (add STRIPE_SECRET_KEY)",
    stripeAlreadyPaid: "✅ Paid via Stripe",
    stripeGenerating: "Generating...",
    // Weekly Summary
    weeklyTabLabel: "Weekly",
    weeklySummaryTitle: "Weekly Summary",
    weeklyPeriod: "Period",
    weeklyEmployee: "Employee",
    weeklyJobs: "Jobs",
    weeklyLabor: "Labor",
    weeklyParts: "Parts",
    weeklyTax: "Tax (8.25%)",
    weeklyNet: "Net Payout",
    weeklyTotal: "TOTAL",
    weeklyLoading: "Loading...",
    weeklyNoData: "No completed jobs this week",
    // Call Logs
    callLogsTitle: "Call Logs",
    callLogsFrom: "From",
    callLogsTo: "To",
    callLogsStatus: "Status",
    callLogsStatusAll: "All",
    callLogsStatusCompleted: "Booked",
    callLogsStatusNoBooking: "Client hung up",
    callLogsStatusError: "Error",
    callLogsApply: "Apply",
    callLogsExportCsv: "Export CSV",
    callLogsThWhen: "Date / Time",
    callLogsThPhone: "Phone",
    callLogsThStatus: "Status",
    callLogsThDuration: "Duration (s)",
    callLogsThBooking: "Booking",
    callLogsOpenBooking: "Open",
    callLogsEmpty: "No calls found",
    callLogsError: "Failed to load call logs",
    callLogsTranscriptTitle: "Call Transcript",
    callLogsTranscriptEmpty: "No transcript available",
    callLogsTranscriptAgent: "Agent",
    callLogsTranscriptCustomer: "Customer",
    callLogsRecording: "Call Recording",
    callLogsRecordingUnsupported: "Your browser does not support audio playback.",
    callLogsCallBack: "Call back",
    callLogsCallingBack: "Calling…",
    callLogsCallBackOk: "Your phone will ring shortly",
    callLogsCallBackErr: "Failed to initiate call",
    callLogsCount: (n: number) => `${n} call${n === 1 ? "" : "s"}`,
    callLogsDelete: "Delete",
    callLogsDeleteConfirm: "Delete this call record?",
    callLogsDeleteOk: "Record deleted",
    callLogsDeleteErr: "Failed to delete",
    callLogsDeletedAt: "Deleted",
    callLogsRestore: "Restore",
    callLogsRestoreOk: "Record restored",
    callLogsRestoreErr: "Failed to restore",
    callLogsRestoreExpired: "Restore window expired (90 days)",
    callLogsShowDeleted: "Show deleted",
    callLogsHideDeleted: "Hide deleted",
    // Downloads section (global receipt downloads in Reports tab)
    downloadsTabLabel: "Downloads",
    downloadsTitle: "Receipt Downloads (all bookings)",
    downloadsFilterBookingId: "Booking ID",
    downloadsFilterBookingPlaceholder: "optional",
    downloadsApplyFilters: "Apply Filters",
    downloadsSuspiciousOnly: "⚠ Suspicious only",
    downloadsExporting: "Exporting…",
    downloadsEmpty: "No receipt downloads match those filters.",
    downloadsThWhen: "When",
    downloadsThClient: "Client / Booking",
    downloadsThActor: "Actor",
    downloadsThIpLocation: "IP / Location",
    downloadsThBrowser: "Browser",
    downloadsNoSuspicious: "No suspicious downloads found.",
    downloadsSuspiciousBadge: "⚠ Suspicious",
    downloadsCount: (n: number) => `${n} download${n === 1 ? "" : "s"}`,
    downloadsSuspiciousCount: (n: number) => `⚠ ${n} suspicious`,
    downloadsOf: "of",
    downloadsTotal: "total",
    downloadsErrorLoad: "Error loading downloads",
    downloadsErrorConnection: "Connection error",
    downloadsErrorExport: "Could not export CSV",
    // Booking-level calls section
    bookingCallsToggleShow: "📞 Show linked calls",
    bookingCallsToggleHide: "📞 Hide calls",
    bookingCallsEmpty: "No calls linked to this booking",
    bookingCallsLoading: "Loading calls…",
    bookingCallsOpenTranscript: "Transcript",
    callLogsShowing: (shown: number, total: number) => `Showing ${shown} of ${total}`,
    callLogsPrev: "Previous",
    callLogsNext: "Next",
    callLogsPage: (page: number, total: number) => `Page ${page} of ${total}`,
    photosShow: "📷 Photos & Signature",
    photosHide: "📷 Hide Photos",
    photosEmpty: "No photos",
    sigNone: "No signature",
    sigTitle: "Client Signature",
    cabinetBtn: "Cabinet",
    cabinetTitle: "Employee Cabinet",
    cabinetNoBookings: "No assigned bookings",
    cabinetCloseJob: "Close Job",
    cabinetCloseTitle: "Close Job (Admin)",
    cabinetBookingsLabel: "Bookings",
    // date locale
    dateLocale: "en-US",
  },
} as const;

export type TranslationKey = keyof typeof translations["ru"];

interface AdminLangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: typeof translations[Lang];
}

const AdminLangContext = createContext<AdminLangContextType>({
  lang: "ru",
  setLang: () => {},
  t: translations.ru,
});

export function AdminLangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      const stored = localStorage.getItem("adminLang");
      if (stored === "ru" || stored === "en") return stored;
      return "ru";
    } catch { return "ru"; }
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    try { localStorage.setItem("adminLang", l); } catch {}
  }, []);

  return (
    <AdminLangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </AdminLangContext.Provider>
  );
}

export function useAdminLang() {
  return useContext(AdminLangContext);
}
