import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from "react";

export type EmpLang = "en" | "ru" | "es" | "tr" | "az" | "uk" | "kk" | "ky" | "uz";

export const translations: Record<EmpLang, Record<string, string>> = {
  en: {
    title: "Technician Dashboard",
    phone: "Phone",
    pin: "PIN",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalidLogin: "Invalid phone or PIN",
    connError: "Connection error",
    hello: "Hello,",
    logout: "Logout",
    myJobs: "Dental Service Jobs",
    calendarTab: "Calendar",
    calTitle: "My Schedule",
    calWeek: "Week",
    calMonth: "Month",
    calYear: "Year",
    calToday: "Today",
    calAllEmployees: "All",
    calNoEvents: "No jobs in this period",
    calLoading: "Loading…",
    calDragHint: "Tap Move or ⋮⋮, then tap the new day/time slot",
    calSerial: "Serial #",
    calTechnician: "Technician",
    calOverdue: "Overdue",
    calRescheduleOk: "Schedule updated",
    calRescheduleErr: "Could not reschedule",
    calStatusCompleted: "Completed",
    calStatusApproved: "Confirmed",
    calStatusPending: "Pending",
    calBizAll: "All",
    calBizAppliance: "Appliance",
    calBizDental: "Dental",
    calTapHint: "Tap a day for jobs. Move → full calendar with ← → and «« »» (month/year) + time",
    calMovePickActive: "Pick a new day or time slot",
    calMovePickCancel: "Cancel",
    calMoveNotAllowed: "Completed and cancelled jobs cannot be moved. Pick an active job.",
    calMoveJob: "Move",
    calPickTime: "Pick a time",
    calOpenCrm: "Open job",
    calBackToCalendar: "Back to calendar",
    calNewBooking: "+ Booking",
    calEditBooking: "Edit",
    calBookingCreateTitle: "New booking",
    calBookingEditTitle: "Edit booking",
    calBookingTimeReq: "Time *",
    calBookingNameReq: "Client name *",
    calBookingPhoneReq: "Phone *",
    calBookingEmail: "Email",
    calBookingCity: "City",
    calBookingZip: "ZIP",
    calBookingErrEmail: "Invalid email address",
    calBookingAssignTech: "Assign technician",
    calBookingUnassigned: "Unassigned",
    calBookingAddress: "Address",
    calBookingEquipAppliance: "Appliance / equipment",
    calBookingEquipDental: "Equipment name",
    calBookingProblemAppliance: "Issue description",
    calBookingProblemDental: "Nature of the problem",
    calBookingBizType: "Service type",
    calBookingCancel: "Cancel",
    calBookingCreateBtn: "Create booking",
    calBookingSaveBtn: "Save",
    calBookingSaving: "Saving…",
    calBookingErrNamePhone: "Name and phone required",
    calBookingErrSlotTaken: "This time slot is already taken",
    calBookingErrServer: "Server error",
    calBookingSavedOk: "Booking saved",
    calBookingNext: "Next",
    payroll: "Payroll",
    profile: "Profile",
    refresh: "Refresh",
    noJobs: "No assigned jobs yet",
    completed: "Completed",
    pending: "Pending",
    confirmed: "Confirmed",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Done",
    paid: "Paid",
    cancelled: "Cancelled",
    period: "Period",
    jobsCount: "Jobs",
    gross: "Gross",
    deductions: "Deductions",
    net: "Net",
    noPayroll: "No payroll records yet",
    car: "Car",
    plate: "Plate",
    closeJob: "Close Job",
    downloadReceipt: "Download Receipt",
    generating: "Generating...",
    repairAmount: "Repair Amount ($)",
    workPerformed: "Work Performed",
    workPlaceholder: "Describe what was done...",
    partsReplaced: "Parts Replaced",
    addPart: "+ Add Part",
    paymentMethod: "Payment Method",
    cash: "Cash",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Open Stripe Dashboard",
    tapToPayInstruction: "Open the Stripe Dashboard app → create a payment → tap client's card",
    zelleInfo: "Send to: hitechrepairgroup@gmail.com",
    openPaymentLink: "Open Payment Link",
    online: "Online (Stripe)",
    clientReceiptLang: "Client Receipt Language",
    cancel: "Cancel",
    followUpBtn: "Reschedule / Follow-up",
    followUpTitle: "Follow-up Visit",
    followUpHint: "Same job · assignment stays with you · frees old slot",
    followUpNewDate: "New date",
    followUpNewTime: "New time",
    followUpSave: "Save Follow-up",
    followUpSaving: "Saving…",
    followUpDateTimeRequired: "Date and time required",
    submit: "Submit",
    repairAmountReq: "Repair Amount is required",
    workPerformedReq: "Work Performed is required",
    errorClosing: "Error closing job",
    address: "Address",
    appliance: "Dental Equipment",
    brandModel: "Brand/Model",
    date: "Date",
    time: "Time",
    notes: "Notes",
    call: "Call",
    smsAction: "SMS",
    emailAction: "Email",
    navigate: "Navigate",
    receiptError: "Could not generate receipt. Please try again.",
    noProfile: "Loading profile...",
    estimateSent: "Estimate sent",
    estimateEdit: "Edit & Resend",
    estimateView: "View",
    estimateDownload: "PDF",
    estimateViewError: "Could not open estimate. Please try again.",
    estimateEditTitle: "Edit Estimate",
    sendEstimate: "Send Estimate",
    estimateTitle: "Create Estimate",
    estimateItems: "Service Items",
    addItem: "+ Add Item",
    itemDesc: "Description",
    itemCat: "Category",
    itemQty: "Qty",
    itemPrice: "Price ($)",
    estimateNotes: "Notes (optional)",
    estimateNotesPlaceholder: "Additional notes for the client...",
    estimateSend: "Send to Client",
    estimateSending: "Sending...",
    estimateSuccess: "Estimate sent!",
    estimateErr: "Error sending estimate",
    noTax: "No tax (discount)",
    estimateSubtotal: "Subtotal",
    estimateTaxLine: "Tax (8.25%)",
    estimateTotalLine: "Total",
    fromPricebook: "From Pricebook",
    customItem: "Custom",
    partsCost: "Parts Cost (actual, for reports $)",
    partsCostHint: "Internal only — not shown to client",
    searchJobs: "Search by name, phone, date, address…",
    searchClear: "Clear",
    tabActive: "Active",
    archiveJob: "Move to Archive",
    restore: "Restore",
    archived: "Archived",
    noArchived: "No archived jobs",
    archiving: "Archiving...",
    restoring: "Restoring...",
    sendReview: "⭐ Request Review",
    sendReviewWa: "WhatsApp",
    sendingReview: "Sending...",
    reviewSent: "Review link sent!",
    notifyMethod: "Send Payment Link Via",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Both",
    clientContact: "Client Contact",
    noContactInfo: "No contact info on file",
    noNotificationWillBeSent: "no notification will be sent",
    statsClosed: "Total Closed",
    statsRevenue: "Total Revenue",
    statsMonth: "This Month",
    statsMonthRev: "This Month $",
    statsWeek: "This Week",
    statsWeekJobs: "jobs this week",
    statsWeekLabor: "Labor",
    statsWeekParts: "Parts",
    statsWeekTax: "Tax (8.25%)",
    statsWeekNet: "Your net",
    statsJobs: "jobs",
    statsTab: "Stats",
    faceIdFailed: "Face ID failed. Enter password.",
    faceIdRegFailed: "Could not enable Face ID",
    fidEnableTitle: "Enable Face ID?",
    fidEnableDesc: "Sign in with one touch, no password needed.\nYour face / fingerprint never leaves your device.",
    fidEnable: "Enable Face ID / Fingerprint",
    fidRegistering: "Registering...",
    fidSkip: "Skip",
    fidSignIn: "Sign in with Face ID",
    fidChecking: "Checking...",
    fidUsePassword: "Sign in with password",
    photosBtn: "📷 Photos",
    photoModal: "Job Photos",
    photoAdd: "Take Photo",
    photoGallery: "Choose from Gallery (up to 10)",
    photoLoading: "Loading...",
    photoNone: "No photos yet",
    photoDelete: "Delete",
    photoUploadFail: "Upload failed",
    sigTitle: "Client Signature",
    sigClear: "Clear",
    sigDraw: "Sign here (optional)",
    sigConsentText: "By signing, the client authorizes HTR Dental to perform the described repairs. Electronic signature valid under Texas law (TUETA).",
    sigOptional: "(optional)",
    editEmail: "Edit Email",
    emailSaved: "Email saved",
    emailSaveErr: "Error saving email",
    addEmail: "Add Email",
  },
  ru: {
    title: "Портал сотрудника",
    phone: "Телефон",
    pin: "ПИН-код",
    signIn: "Войти",
    signingIn: "Вход...",
    invalidLogin: "Неверный телефон или ПИН",
    connError: "Ошибка соединения",
    hello: "Привет,",
    logout: "Выйти",
    myJobs: "Мои заказы",
    calendarTab: "Календарь",
    calTitle: "Моё расписание",
    calWeek: "Неделя",
    calMonth: "Месяц",
    calYear: "Год",
    calToday: "Сегодня",
    calAllEmployees: "Все",
    calNoEvents: "Нет заказов в этом периоде",
    calLoading: "Загрузка…",
    calDragHint: "Нажмите «Перенести» или ⋮⋮, затем выберите новый день/слот",
    calSerial: "Серийный №",
    calTechnician: "Техник",
    calOverdue: "Просрочен",
    calRescheduleOk: "Время обновлено",
    calRescheduleErr: "Не удалось перенести",
    calStatusCompleted: "Завершён",
    calStatusApproved: "Подтверждён",
    calStatusPending: "Ожидает",
    calBizAll: "Все",
    calBizAppliance: "Appliance",
    calBizDental: "Dental",
    calTapHint: "День → список. «Перенести» → календарь с ← → и «« »» (месяц/год) + время",
    calMovePickActive: "Выберите новый день или слот времени",
    calMovePickCancel: "Отмена",
    calMoveNotAllowed: "Завершённые и отменённые заказы нельзя перенести. Выберите активную заявку.",
    calMoveJob: "Перенести",
    calPickTime: "Выберите время",
    calOpenCrm: "Открыть заказ",
    calBackToCalendar: "Назад к календарю",
    calNewBooking: "+ Заявка",
    calEditBooking: "Изменить",
    calBookingCreateTitle: "Новая заявка",
    calBookingEditTitle: "Редактирование заявки",
    calBookingTimeReq: "Время *",
    calBookingNameReq: "Имя клиента *",
    calBookingPhoneReq: "Телефон *",
    calBookingEmail: "Электронная почта",
    calBookingCity: "Город",
    calBookingZip: "ZIP",
    calBookingErrEmail: "Некорректный email",
    calBookingAssignTech: "Назначить техника",
    calBookingUnassigned: "Не назначен",
    calBookingAddress: "Адрес",
    calBookingEquipAppliance: "Оборудование",
    calBookingEquipDental: "Наименование оборудования",
    calBookingProblemAppliance: "Характер поломки",
    calBookingProblemDental: "Характер неисправности",
    calBookingBizType: "Тип сервиса",
    calBookingCancel: "Отмена",
    calBookingCreateBtn: "Создать заявку",
    calBookingSaveBtn: "Сохранить",
    calBookingSaving: "Сохранение…",
    calBookingErrNamePhone: "Укажите имя и телефон",
    calBookingErrSlotTaken: "Этот слот уже занят",
    calBookingErrServer: "Ошибка сервера",
    calBookingSavedOk: "Заявка сохранена",
    calBookingNext: "Далее",
    payroll: "Зарплата",
    profile: "Профиль",
    refresh: "Обновить",
    noJobs: "Назначенных заказов пока нет",
    completed: "Завершено",
    pending: "Ожидает",
    confirmed: "Подтверждено",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Готово",
    paid: "Оплачено",
    cancelled: "Отменено",
    period: "Период",
    jobsCount: "Заказов",
    gross: "Всего",
    deductions: "Вычеты",
    net: "К выплате",
    noPayroll: "Записей о зарплате пока нет",
    car: "Авто",
    plate: "Номер",
    closeJob: "Закрыть заказ",
    downloadReceipt: "Скачать чек",
    generating: "Создание...",
    repairAmount: "Сумма ремонта ($)",
    workPerformed: "Выполненная работа",
    workPlaceholder: "Опишите, что было сделано...",
    partsReplaced: "Замененные детали",
    addPart: "+ Добавить деталь",
    paymentMethod: "Способ оплаты",
    cash: "Наличные",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Открыть Stripe Dashboard",
    tapToPayInstruction: "Откройте Stripe Dashboard → создайте платёж → поднесите карту клиента",
    zelleInfo: "Отправить: hitechrepairgroup@gmail.com",
    openPaymentLink: "Открыть ссылку оплаты",
    online: "Онлайн (Stripe)",
    clientReceiptLang: "Язык чека клиента",
    cancel: "Отмена",
    followUpBtn: "Перенос / Повторный визит",
    followUpTitle: "Повторный визит",
    followUpHint: "Тот же заказ · мастер не меняется · старый слот освобождается",
    followUpNewDate: "Новая дата",
    followUpNewTime: "Новое время",
    followUpSave: "Сохранить повторный визит",
    followUpSaving: "Сохранение…",
    followUpDateTimeRequired: "Укажите дату и время",
    submit: "Отправить",
    repairAmountReq: "Сумма ремонта обязательна",
    workPerformedReq: "Описание работы обязательно",
    errorClosing: "Ошибка при закрытии заказа",
    address: "Адрес",
    appliance: "Техника",
    brandModel: "Марка/Модель",
    date: "Дата",
    time: "Время",
    notes: "Заметки",
    call: "Позвонить",
    smsAction: "SMS",
    emailAction: "Email",
    navigate: "Маршрут",
    receiptError: "Не удалось создать чек. Попробуйте еще раз.",
    noProfile: "Загрузка профиля...",
    estimateSent: "Смета отправлена",
    estimateEdit: "Изменить и отправить",
    estimateView: "Просмотр",
    estimateDownload: "PDF",
    estimateViewError: "Не удалось открыть смету. Попробуйте ещё раз.",
    estimateEditTitle: "Редактировать смету",
    sendEstimate: "Отправить смету",
    estimateTitle: "Создать смету",
    estimateItems: "Позиции услуг",
    addItem: "+ Добавить позицию",
    itemDesc: "Описание",
    itemCat: "Категория",
    itemQty: "Кол-во",
    itemPrice: "Цена ($)",
    estimateNotes: "Заметки (необязательно)",
    estimateNotesPlaceholder: "Дополнительные заметки для клиента...",
    estimateSend: "Отправить клиенту",
    estimateSending: "Отправляем...",
    estimateSuccess: "Смета отправлена!",
    estimateErr: "Ошибка отправки сметы",
    noTax: "Без налога (скидка)",
    estimateSubtotal: "Подытог",
    estimateTaxLine: "Налог (8.25%)",
    estimateTotalLine: "Итого",
    fromPricebook: "Из прайс-листа",
    customItem: "Своё",
    partsCost: "Стоимость запчастей (факт., для отчётов $)",
    partsCostHint: "Только для внутреннего учёта — клиент не видит",
    searchJobs: "Поиск: имя, телефон, дата, адрес…",
    searchClear: "Сбросить",
    tabActive: "Активные",
    archiveJob: "В архив",
    restore: "Восстановить",
    archived: "Архив",
    noArchived: "Архив пуст",
    archiving: "Архивирование...",
    restoring: "Восстановление...",
    sendReview: "⭐ Запросить отзыв",
    sendReviewWa: "WhatsApp",
    sendingReview: "Отправляем...",
    reviewSent: "Ссылка на отзыв отправлена!",
    notifyMethod: "Отправить ссылку на оплату через",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Оба",
    clientContact: "Контакты клиента",
    noContactInfo: "Контактных данных нет",
    noNotificationWillBeSent: "уведомление не будет отправлено",
    statsClosed: "Всего закрыто",
    statsRevenue: "Общая выручка",
    statsMonth: "Этот месяц",
    statsMonthRev: "Этот месяц $",
    statsWeek: "Эта неделя",
    statsWeekJobs: "заказов за неделю",
    statsWeekLabor: "Работа",
    statsWeekParts: "Запчасти",
    statsWeekTax: "Налог (8.25%)",
    statsWeekNet: "Ваша доля",
    statsJobs: "заказов",
    statsTab: "Статистика",
    faceIdFailed: "Face ID не прошёл. Введите пароль.",
    faceIdRegFailed: "Не удалось включить Face ID",
    fidEnableTitle: "Включить Face ID?",
    fidEnableDesc: "Вход одним касанием без пароля.\nВаше лицо / отпечаток не покидает устройство.",
    fidEnable: "Включить Face ID / Fingerprint",
    fidRegistering: "Регистрация...",
    fidSkip: "Пропустить",
    fidSignIn: "Войти через Face ID",
    fidChecking: "Проверка...",
    fidUsePassword: "Войти по паролю",
    photosBtn: "📷 Фото",
    photoModal: "Фото заказа",
    photoAdd: "Сделать фото",
    photoGallery: "Выбрать из галереи (до 10 фото)",
    photoLoading: "Загрузка...",
    photoNone: "Фото нет",
    photoDelete: "Удалить",
    photoUploadFail: "Ошибка загрузки",
    sigTitle: "Подпись клиента",
    sigClear: "Очистить",
    sigDraw: "Нарисуйте подпись (опционально)",
    sigConsentText: "Подписывая, клиент разрешает HTR Dental выполнить описанный ремонт. Электронная подпись действительна по законодательству Техаса (TUETA).",
    sigOptional: "(опционально)",
    editEmail: "Изменить Email",
    emailSaved: "Email сохранён",
    emailSaveErr: "Ошибка сохранения Email",
    addEmail: "Добавить Email",
  },
  es: {
    title: "Portal del empleado",
    phone: "Teléfono",
    pin: "PIN",
    signIn: "Iniciar sesión",
    signingIn: "Iniciando sesión...",
    invalidLogin: "Teléfono o PIN inválido",
    connError: "Error de conexión",
    hello: "Hola,",
    logout: "Cerrar sesión",
    myJobs: "Mis trabajos",
    payroll: "Nómina",
    profile: "Perfil",
    refresh: "Actualizar",
    noJobs: "Aún no hay trabajos asignados",
    completed: "Completado",
    pending: "Pendiente",
    confirmed: "Confirmado",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Hecho",
    paid: "Pagado",
    cancelled: "Cancelado",
    period: "Período",
    jobsCount: "Trabajos",
    gross: "Bruto",
    deductions: "Deducciones",
    net: "Neto",
    noPayroll: "Aún no hay registros de nómina",
    car: "Coche",
    plate: "Placa",
    closeJob: "Cerrar trabajo",
    downloadReceipt: "Descargar recibo",
    generating: "Generando...",
    repairAmount: "Monto de reparación ($)",
    workPerformed: "Trabajo realizado",
    workPlaceholder: "Describe lo que se hizo...",
    partsReplaced: "Piezas reemplazadas",
    addPart: "+ Añadir pieza",
    paymentMethod: "Método de pago",
    cash: "Efectivo",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Abrir Stripe Dashboard",
    tapToPayInstruction: "Abre la app Stripe Dashboard → crea un pago → acerca la tarjeta del cliente",
    zelleInfo: "Enviar a: hitechrepairgroup@gmail.com",
    openPaymentLink: "Abrir enlace de pago",
    online: "En línea (Stripe)",
    clientReceiptLang: "Idioma del recibo del cliente",
    cancel: "Cancelar",
    followUpBtn: "Reprogramar / Seguimiento",
    followUpTitle: "Visita de seguimiento",
    followUpHint: "Mismo trabajo · asignación sin cambios · libera el horario anterior",
    followUpNewDate: "Nueva fecha",
    followUpNewTime: "Nueva hora",
    followUpSave: "Guardar seguimiento",
    followUpSaving: "Guardando…",
    followUpDateTimeRequired: "Fecha y hora requeridas",
    submit: "Enviar",
    repairAmountReq: "El monto de la reparación es obligatorio",
    workPerformedReq: "El trabajo realizado es obligatorio",
    errorClosing: "Error al cerrar el trabajo",
    address: "Dirección",
    appliance: "Equipo dental",
    brandModel: "Marca/Modelo",
    date: "Fecha",
    time: "Hora",
    notes: "Notas",
    call: "Llamar",
    smsAction: "SMS",
    emailAction: "Email",
    navigate: "Navegar",
    receiptError: "No se pudo generar el recibo. Por favor, inténtelo de nuevo.",
    noProfile: "Cargando perfil...",
    estimateSent: "Presupuesto enviado",
    estimateEdit: "Editar y reenviar",
    estimateView: "Ver",
    estimateDownload: "PDF",
    estimateViewError: "No se pudo abrir el presupuesto. Inténtelo de nuevo.",
    estimateEditTitle: "Editar presupuesto",
    sendEstimate: "Enviar presupuesto",
    estimateTitle: "Crear presupuesto",
    estimateItems: "Servicios",
    addItem: "+ Agregar elemento",
    itemDesc: "Descripción",
    itemCat: "Categoría",
    itemQty: "Cant.",
    itemPrice: "Precio ($)",
    estimateNotes: "Notas (opcional)",
    estimateNotesPlaceholder: "Notas adicionales para el cliente...",
    estimateSend: "Enviar al cliente",
    estimateSending: "Enviando...",
    estimateSuccess: "¡Presupuesto enviado!",
    estimateErr: "Error al enviar presupuesto",
    noTax: "Sin impuesto (descuento)",
    estimateSubtotal: "Subtotal",
    estimateTaxLine: "Impuesto (8.25%)",
    estimateTotalLine: "Total",
    fromPricebook: "Del catálogo",
    customItem: "Personalizado",
    partsCost: "Costo de partes (real, para reportes $)",
    partsCostHint: "Solo interno — el cliente no lo ve",
    searchJobs: "Buscar: nombre, teléfono, fecha, dirección…",
    searchClear: "Limpiar",
    tabActive: "Activos",
    archiveJob: "Archivar",
    restore: "Restaurar",
    archived: "Archivados",
    noArchived: "No hay trabajos archivados",
    archiving: "Archivando...",
    restoring: "Restaurando...",
    sendReview: "⭐ Pedir reseña",
    sendReviewWa: "WhatsApp",
    sendingReview: "Enviando...",
    reviewSent: "¡Enlace de reseña enviado!",
    notifyMethod: "Enviar enlace de pago por",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Ambos",
    clientContact: "Contacto del cliente",
    noContactInfo: "Sin información de contacto",
    noNotificationWillBeSent: "no se enviará notificación",
    statsClosed: "Total cerrado",
    statsRevenue: "Ingresos totales",
    statsMonth: "Este mes",
    statsMonthRev: "Este mes $",
    statsWeek: "Esta semana",
    statsWeekJobs: "trabajos esta semana",
    statsWeekLabor: "Mano de obra",
    statsWeekParts: "Refacciones",
    statsWeekTax: "Impuesto (8.25%)",
    statsWeekNet: "Tu parte neta",
    statsJobs: "trabajos",
    statsTab: "Estadísticas",
    faceIdFailed: "Face ID fallido. Ingrese contraseña.",
    faceIdRegFailed: "No se pudo activar Face ID",
    fidEnableTitle: "¿Activar Face ID?",
    fidEnableDesc: "Ingrese con un toque, sin contraseña.\nSu cara / huella nunca sale del dispositivo.",
    fidEnable: "Activar Face ID / Huella",
    fidRegistering: "Registrando...",
    fidSkip: "Omitir",
    fidSignIn: "Entrar con Face ID",
    fidChecking: "Verificando...",
    fidUsePassword: "Entrar con contraseña",
    photosBtn: "📷 Fotos",
    photoModal: "Fotos del trabajo",
    photoAdd: "Tomar foto",
    photoGallery: "Elegir de galería (hasta 10)",
    photoLoading: "Cargando...",
    photoNone: "Sin fotos aún",
    photoDelete: "Eliminar",
    photoUploadFail: "Error al subir",
    sigTitle: "Firma del cliente",
    sigClear: "Limpiar",
    sigDraw: "Firme aquí (opcional)",
    sigConsentText: "Al firmar, el cliente autoriza a HTR Dental a realizar las reparaciones descritas. Firma electrónica válida bajo la ley de Texas (TUETA).",
    sigOptional: "(opcional)",
    editEmail: "Editar Email",
    emailSaved: "Email guardado",
    emailSaveErr: "Error al guardar email",
    addEmail: "Agregar Email",
  },
  tr: {
    title: "Personel Portalı",
    phone: "Telefon",
    pin: "PIN",
    signIn: "Giriş Yap",
    signingIn: "Giriş yapılıyor...",
    invalidLogin: "Geçersiz telefon veya PIN",
    connError: "Bağlantı hatası",
    hello: "Merhaba,",
    logout: "Çıkış Yap",
    myJobs: "İşlerim",
    calendarTab: "Takvim",
    calTitle: "Programım",
    calWeek: "Hafta",
    calMonth: "Ay",
    calYear: "Yıl",
    calToday: "Bugün",
    calAllEmployees: "Tümü",
    calNoEvents: "Bu dönemde iş yok",
    calLoading: "Yükleniyor…",
    calDragHint: "«Taşı» düğmesine basın, sonra yeni gün/saat seçin",
    calSerial: "Seri No",
    calTechnician: "Teknisyen",
    calOverdue: "Gecikmiş",
    calRescheduleOk: "Program güncellendi",
    calRescheduleErr: "Taşınamadı",
    calStatusCompleted: "Tamamlandı",
    calStatusApproved: "Onaylandı",
    calStatusPending: "Beklemede",
    calBizAll: "Tümü",
    calBizAppliance: "Appliance",
    calBizDental: "Dental",
    calTapHint: "Güne dokunun. Taşı → tam ay takvimi (← → «« »») + saat",
    calMovePickActive: "Yeni gün veya saat seçin",
    calMovePickCancel: "İptal",
    calMoveNotAllowed: "Tamamlanan ve iptal edilen işler taşınamaz. Aktif iş seçin.",
    calMoveJob: "Taşı",
    calPickTime: "Saat seçin",
    calOpenCrm: "İşi aç",
    calBackToCalendar: "Takvime dön",
    calNewBooking: "+ Kayıt",
    calEditBooking: "Düzenle",
    calBookingCreateTitle: "Yeni kayıt",
    calBookingEditTitle: "Kaydı düzenle",
    calBookingTimeReq: "Saat *",
    calBookingNameReq: "Müşteri adı *",
    calBookingPhoneReq: "Telefon *",
    calBookingEmail: "E-posta",
    calBookingCity: "Şehir",
    calBookingZip: "ZIP",
    calBookingErrEmail: "Geçersiz e-posta",
    calBookingAssignTech: "Teknisyen ata",
    calBookingUnassigned: "Atanmamış",
    calBookingAddress: "Adres",
    calBookingEquipAppliance: "Cihaz",
    calBookingEquipDental: "Ekipman adı",
    calBookingProblemAppliance: "Arıza türü",
    calBookingProblemDental: "Arıza türü",
    calBookingBizType: "Hizmet türü",
    calBookingCancel: "İptal",
    calBookingCreateBtn: "Kayıt oluştur",
    calBookingSaveBtn: "Kaydet",
    calBookingSaving: "Kaydediliyor…",
    calBookingErrNamePhone: "Ad ve telefon girin",
    calBookingErrSlotTaken: "Bu saat dolu",
    calBookingErrServer: "Sunucu hatası",
    calBookingSavedOk: "Kayıt kaydedildi",
    calBookingNext: "İleri",
    payroll: "Maaş",
    profile: "Profil",
    refresh: "Yenile",
    noJobs: "Henüz atanmış iş yok",
    completed: "Tamamlandı",
    pending: "Beklemede",
    confirmed: "Onaylandı",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Bitti",
    paid: "Ödendi",
    cancelled: "İptal edildi",
    period: "Dönem",
    jobsCount: "İş sayısı",
    gross: "Brüt",
    deductions: "Kesintiler",
    net: "Net",
    noPayroll: "Henüz maaş kaydı yok",
    car: "Araç",
    plate: "Plaka",
    closeJob: "İşi Kapat",
    downloadReceipt: "Fişi İndir",
    generating: "Oluşturuluyor...",
    repairAmount: "Onarım Tutarı ($)",
    workPerformed: "Yapılan İş",
    workPlaceholder: "Ne yapıldığını açıklayın...",
    partsReplaced: "Değişen Parçalar",
    addPart: "+ Parça Ekle",
    paymentMethod: "Ödeme Yöntemi",
    cash: "Nakit",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Stripe Dashboard'u Aç",
    tapToPayInstruction: "Stripe Dashboard uygulamasını aç → ödeme oluştur → müşteri kartını yaklaştır",
    zelleInfo: "Gönder: hitechrepairgroup@gmail.com",
    openPaymentLink: "Ödeme Linkini Aç",
    online: "Çevrimiçi (Stripe)",
    clientReceiptLang: "Müşteri Fiş Dili",
    cancel: "İptal",
    followUpBtn: "Yeniden planla / Takip",
    followUpTitle: "Takip Ziyareti",
    followUpHint: "Aynı iş · atama değişmez · eski slot boşalır",
    followUpNewDate: "Yeni tarih",
    followUpNewTime: "Yeni saat",
    followUpSave: "Takibi Kaydet",
    followUpSaving: "Kaydediliyor…",
    followUpDateTimeRequired: "Tarih ve saat gerekli",
    submit: "Gönder",
    repairAmountReq: "Onarım tutarı gerekli",
    workPerformedReq: "Yapılan iş gerekli",
    errorClosing: "İş kapatılırken hata oluştu",
    address: "Adres",
    appliance: "Cihaz",
    brandModel: "Marka/Model",
    date: "Tarih",
    time: "Saat",
    notes: "Notlar",
    call: "Ara",
    navigate: "Yol Tarifi",
    receiptError: "Fiş oluşturulamadı. Lütfen tekrar deneyin.",
    noProfile: "Profil yükleniyor...",
    sendEstimate: "Teklif Gönder",
    estimateTitle: "Teklif Oluştur",
    estimateItems: "Hizmet Kalemleri",
    addItem: "+ Kalem Ekle",
    itemDesc: "Açıklama",
    itemCat: "Kategori",
    itemQty: "Adet",
    itemPrice: "Fiyat ($)",
    estimateNotes: "Notlar (isteğe bağlı)",
    estimateNotesPlaceholder: "Müşteri için ek notlar...",
    estimateSend: "Müşteriye Gönder",
    estimateSending: "Gönderiliyor...",
    estimateSuccess: "Teklif gönderildi!",
    estimateErr: "Teklif gönderme hatası",
    noTax: "Vergisiz (indirim)",
    estimateSubtotal: "Ara toplam",
    estimateTaxLine: "Vergi (8.25%)",
    estimateTotalLine: "Toplam",
    fromPricebook: "Fiyat listesinden",
    customItem: "Özel",
    partsCost: "Parça maliyeti (gerçek, raporlar için $)",
    partsCostHint: "Yalnızca dahili — müşteri görmez",
    searchJobs: "Ara: ad, telefon, tarih, adres…",
    searchClear: "Temizle",
    tabActive: "Aktif",
    archiveJob: "Arşivle",
    restore: "Geri Yükle",
    archived: "Arşiv",
    noArchived: "Arşivlenmiş iş yok",
    archiving: "Arşivleniyor...",
    restoring: "Geri yükleniyor...",
    sendReview: "⭐ Yorum İste",
    sendReviewWa: "WhatsApp",
    sendingReview: "Gönderiliyor...",
    reviewSent: "Yorum bağlantısı gönderildi!",
    notifyMethod: "Ödeme bağlantısını gönder",
    viaEmail: "E-posta",
    viaSMS: "SMS",
    viaBoth: "İkisi de",
    clientContact: "Müşteri iletişim bilgisi",
    noContactInfo: "İletişim bilgisi yok",
    noNotificationWillBeSent: "bildirim gönderilmeyecek",
    statsClosed: "Toplam Kapatılan",
    statsRevenue: "Toplam Gelir",
    statsMonth: "Bu Ay",
    statsMonthRev: "Bu Ay $",
    statsWeek: "Bu Hafta",
    statsWeekJobs: "bu haftaki iş",
    statsWeekLabor: "İşçilik",
    statsWeekParts: "Parçalar",
    statsWeekTax: "Vergi (8.25%)",
    statsWeekNet: "Net payınız",
    statsJobs: "iş",
    statsTab: "İstatistik",
    faceIdFailed: "Face ID başarısız. Şifre girin.",
    faceIdRegFailed: "Face ID etkinleştirilemedi",
    fidEnableTitle: "Face ID etkinleştirilsin mi?",
    fidEnableDesc: "Şifresiz tek dokunuşla giriş yapın.\nYüzünüz / parmak iziniz cihazdan çıkmaz.",
    fidEnable: "Face ID / Parmak İzi Etkinleştir",
    fidRegistering: "Kaydediliyor...",
    fidSkip: "Atla",
    fidSignIn: "Face ID ile Giriş",
    fidChecking: "Kontrol ediliyor...",
    fidUsePassword: "Şifre ile giriş",
    photosBtn: "📷 Fotoğraflar",
    photoModal: "İş Fotoğrafları",
    photoAdd: "Fotoğraf Çek",
    photoGallery: "Galeriden Seç (10'a kadar)",
    photoLoading: "Yükleniyor...",
    photoNone: "Henüz fotoğraf yok",
    photoDelete: "Sil",
    photoUploadFail: "Yükleme hatası",
    sigTitle: "Müşteri İmzası",
    sigClear: "Temizle",
    sigDraw: "Buraya imzalayın (isteğe bağlı)",
    sigConsentText: "İmzalayarak müşteri, HTR Dental'in açıklanan onarımları yapmasını onaylar. Texas hukukuna göre geçerli elektronik imza (TUETA).",
    sigOptional: "(isteğe bağlı)",
    editEmail: "E-posta Düzenle",
    emailSaved: "E-posta kaydedildi",
    emailSaveErr: "E-posta kaydetme hatası",
    addEmail: "E-posta Ekle",
  },
  az: {
    title: "İşçi Portalı",
    phone: "Telefon",
    pin: "PIN",
    signIn: "Daxil ol",
    signingIn: "Daxil olunur...",
    invalidLogin: "Yanlış telefon və ya PIN",
    connError: "Bağlantı xətası",
    hello: "Salam,",
    logout: "Çıxış",
    myJobs: "İşlərim",
    calendarTab: "Cədvəl",
    calTitle: "Cədvəlim",
    calWeek: "Həftə",
    calMonth: "Ay",
    calYear: "İl",
    calToday: "Bu gün",
    calAllEmployees: "Hamısı",
    calNoEvents: "Bu dövrdə iş yoxdur",
    calLoading: "Yüklənir…",
    calDragHint: "«Köçür» düyməsinə basın, sonra yeni gün/vaxt seçin",
    calSerial: "Seriya №",
    calTechnician: "Texnik",
    calOverdue: "Gecikmiş",
    calRescheduleOk: "Cədvəl yeniləndi",
    calRescheduleErr: "Köçürülmə alınmadı",
    calStatusCompleted: "Tamamlandı",
    calStatusApproved: "Təsdiqləndi",
    calStatusPending: "Gözləyir",
    calBizAll: "Hamısı",
    calBizAppliance: "Appliance",
    calBizDental: "Dental",
    calTapHint: "Günə toxunun. Köçür → tam ay təqvimi (← → «« »») + vaxt",
    calMovePickActive: "Yeni gün və ya vaxt seçin",
    calMovePickCancel: "Ləğv",
    calMoveNotAllowed: "Tamamlanmış və ləğv edilmiş işlər köçürülə bilməz. Aktiv iş seçin.",
    calMoveJob: "Köçür",
    calPickTime: "Vaxt seçin",
    calOpenCrm: "İşi aç",
    calBackToCalendar: "Cədvələ qayıt",
    calNewBooking: "+ Yeni qeyd",
    calEditBooking: "Düzəlt",
    calBookingCreateTitle: "Yeni qeyd",
    calBookingEditTitle: "Qeydi redaktə et",
    calBookingTimeReq: "Vaxt *",
    calBookingNameReq: "Müştəri adı *",
    calBookingPhoneReq: "Telefon *",
    calBookingEmail: "E-poçt",
    calBookingCity: "Şəhər",
    calBookingZip: "ZIP",
    calBookingErrEmail: "Yanlış e-poçt",
    calBookingAssignTech: "Texniki təyin et",
    calBookingUnassigned: "Təyin edilməyib",
    calBookingAddress: "Ünvan",
    calBookingEquipAppliance: "Avadanlıq",
    calBookingEquipDental: "Avadanlıq adı",
    calBookingProblemAppliance: "Nasazlıq xarakteri",
    calBookingProblemDental: "Nasazlıq xarakteri",
    calBookingBizType: "Xidmət növü",
    calBookingCancel: "Ləğv",
    calBookingCreateBtn: "Qeyd yarat",
    calBookingSaveBtn: "Saxla",
    calBookingSaving: "Saxlanılır…",
    calBookingErrNamePhone: "Ad və telefon daxil edin",
    calBookingErrSlotTaken: "Bu vaxt artıq doludur",
    calBookingErrServer: "Server xətası",
    calBookingSavedOk: "Qeyd saxlanıldı",
    calBookingNext: "Növbəti",
    payroll: "Maaş",
    profile: "Profil",
    refresh: "Yenilə",
    noJobs: "Hələ təyin olunmuş iş yoxdur",
    completed: "Tamamlandı",
    pending: "Gözləyir",
    confirmed: "Təsdiqləndi",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Hazırdır",
    paid: "Ödənildi",
    cancelled: "Ləğv edildi",
    period: "Dövr",
    jobsCount: "İşlər",
    gross: "Ümumi",
    deductions: "Tutulmalar",
    net: "Xalis",
    noPayroll: "Hələ maaş qeydi yoxdur",
    car: "Maşın",
    plate: "Nömrə",
    closeJob: "İşi Bağla",
    downloadReceipt: "Qəbzi Yüklə",
    generating: "Hazırlanır...",
    repairAmount: "Təmir Məbləği ($)",
    workPerformed: "Görülən İş",
    workPlaceholder: "Nə edildiyini təsvir edin...",
    partsReplaced: "Dəyişdirilmiş Hissələr",
    addPart: "+ Hissə Əlavə Et",
    paymentMethod: "Ödəniş Üsulu",
    cash: "Nağd",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Stripe Dashboard Aç",
    tapToPayInstruction: "Stripe Dashboard tətbiqini açın → ödəniş yaradın → müştəri kartını yaxınlaşdırın",
    zelleInfo: "Göndər: hitechrepairgroup@gmail.com",
    openPaymentLink: "Ödəniş Linkini Aç",
    online: "Onlayn (Stripe)",
    clientReceiptLang: "Müştəri Qəbz Dili",
    cancel: "Ləğv et",
    followUpBtn: "Yenidən planlaşdır / Təkrar ziyarət",
    followUpTitle: "Təkrar ziyarət",
    followUpHint: "Eyni iş · təyinat dəyişmir · köhnə slot boşalır",
    followUpNewDate: "Yeni tarix",
    followUpNewTime: "Yeni vaxt",
    followUpSave: "Təkrar ziyarəti yadda saxla",
    followUpSaving: "Saxlanılır…",
    followUpDateTimeRequired: "Tarix və vaxt tələb olunur",
    submit: "Göndər",
    repairAmountReq: "Təmir məbləği tələb olunur",
    workPerformedReq: "Görülən iş tələb olunur",
    errorClosing: "İşi bağlayarkən xəta",
    address: "Ünvan",
    appliance: "Avadanlıq",
    brandModel: "Marka/Model",
    date: "Tarix",
    time: "Saat",
    notes: "Qeydlər",
    call: "Zəng et",
    smsAction: "SMS",
    emailAction: "E-poçt",
    navigate: "Naviqasiya",
    receiptError: "Qəbz hazırlana bilmədi. Yenidən cəhd edin.",
    noProfile: "Profil yüklənir...",
    estimateSent: "Smeta göndərildi",
    estimateEdit: "Düzəlt və yenidən göndər",
    estimateView: "Bax",
    estimateDownload: "PDF",
    estimateViewError: "Smeta açıla bilmədi. Yenidən cəhd edin.",
    estimateEditTitle: "Smetanı redaktə et",
    sendEstimate: "Smeta Göndər",
    estimateTitle: "Smeta Yarat",
    estimateItems: "Xidmət Maddələri",
    addItem: "+ Maddə Əlavə Et",
    itemDesc: "Təsvir",
    itemCat: "Kateqoriya",
    itemQty: "Say",
    itemPrice: "Qiymət ($)",
    estimateNotes: "Qeydlər (isteğe bağlı)",
    estimateNotesPlaceholder: "Müştəri üçün əlavə qeydlər...",
    estimateSend: "Müştəriyə Göndər",
    estimateSending: "Göndərilir...",
    estimateSuccess: "Smeta göndərildi!",
    estimateErr: "Smeta göndərmə xətası",
    noTax: "Vergisiz (endirim)",
    estimateSubtotal: "Aralıq cəm",
    estimateTaxLine: "Vergi (8.25%)",
    estimateTotalLine: "Cəmi",
    fromPricebook: "Qiymət siyahısından",
    customItem: "Xüsusi",
    partsCost: "Hissə dəyəri (faktiki, hesabatlar üçün $)",
    partsCostHint: "Yalnız daxili — müştəri görmür",
    searchJobs: "Axtar: ad, telefon, tarix, ünvan…",
    searchClear: "Təmizlə",
    tabActive: "Aktiv",
    archiveJob: "Arxivlə",
    restore: "Bərpa et",
    archived: "Arxiv",
    noArchived: "Arxivlənmiş iş yoxdur",
    archiving: "Arxivlənir...",
    restoring: "Bərpa edilir...",
    sendReview: "⭐ Rəy İstə",
    sendReviewWa: "WhatsApp",
    sendingReview: "Göndərilir...",
    reviewSent: "Rəy linki göndərildi!",
    notifyMethod: "Ödəniş linkini göndər",
    viaEmail: "E-poçt",
    viaSMS: "SMS",
    viaBoth: "Hər ikisi",
    clientContact: "Müştəri əlaqəsi",
    noContactInfo: "Əlaqə məlumatı yoxdur",
    noNotificationWillBeSent: "bildiriş göndərilməyəcək",
    statsClosed: "Cəmi Bağlandı",
    statsRevenue: "Ümumi Gəlir",
    statsMonth: "Bu Ay",
    statsMonthRev: "Bu Ay $",
    statsWeek: "Bu Həftə",
    statsWeekJobs: "bu həftəki iş",
    statsWeekLabor: "Əmək",
    statsWeekParts: "Hissələr",
    statsWeekTax: "Vergi (8.25%)",
    statsWeekNet: "Sizin payınız",
    statsJobs: "iş",
    statsTab: "Statistika",
    faceIdFailed: "Face ID uğursuz oldu. Şifrəni daxil edin.",
    faceIdRegFailed: "Face ID aktiv edilə bilmədi",
    fidEnableTitle: "Face ID aktiv edilsin?",
    fidEnableDesc: "Şifrəsiz bir toxunuşla daxil olun.\nÜzünüz / barmaq iziniz cihazdan çıxmır.",
    fidEnable: "Face ID / Barmaq İzi Aktiv Et",
    fidRegistering: "Qeyd edilir...",
    fidSkip: "Keç",
    fidSignIn: "Face ID ilə Daxil Ol",
    fidChecking: "Yoxlanılır...",
    fidUsePassword: "Şifrə ilə daxil ol",
    photosBtn: "📷 Şəkillər",
    photoModal: "İş Şəkilləri",
    photoAdd: "Şəkil çək",
    photoGallery: "Qalereyadan seç (10-a qədər)",
    photoLoading: "Yüklənir...",
    photoNone: "Hələ şəkil yoxdur",
    photoDelete: "Sil",
    photoUploadFail: "Yükləmə xətası",
    sigTitle: "Müştəri İmzası",
    sigClear: "Təmizlə",
    sigDraw: "Buraya imzalayın (ixtiyari)",
    sigConsentText: "İmzalayaraq müştəri HTR Dental-in təsvir olunan təmirləri etməsinə icazə verir. Texas qanunvericiliyinə əsasən etibarlı elektron imza (TUETA).",
    sigOptional: "(ixtiyari)",
    editEmail: "E-poçtu Yenilə",
    emailSaved: "E-poçt qeydə alındı",
    emailSaveErr: "E-poçt saxlama xətası",
    addEmail: "E-poçt Əlavə Et",
  },
  uk: {
    title: "Портал працівника",
    phone: "Телефон",
    pin: "ПІН-код",
    signIn: "Увійти",
    signingIn: "Вхід...",
    invalidLogin: "Невірний телефон або ПІН",
    connError: "Помилка з'єднання",
    hello: "Привіт,",
    logout: "Вийти",
    myJobs: "Мої роботи",
    calendarTab: "Календар",
    calTitle: "Мій графік",
    calWeek: "Тиждень",
    calMonth: "Місяць",
    calYear: "Рік",
    calToday: "Сьогодні",
    calAllEmployees: "Усі",
    calNoEvents: "Немає робіт у цьому періоді",
    calLoading: "Завантаження…",
    calDragHint: "Натисніть «Перенести», потім оберіть новий день/слот",
    calSerial: "Серійний №",
    calTechnician: "Технік",
    calOverdue: "Прострочено",
    calRescheduleOk: "Час оновлено",
    calRescheduleErr: "Не вдалося перенести",
    calStatusCompleted: "Завершено",
    calStatusApproved: "Підтверджено",
    calStatusPending: "Очікує",
    calBizAll: "Усі",
    calBizAppliance: "Appliance",
    calBizDental: "Dental",
    calTapHint: "День → список. «Перенести» → календар з ← → і «« »» (місяць/рік) + час",
    calMovePickActive: "Оберіть новий день або слот часу",
    calMovePickCancel: "Скасувати",
    calMoveNotAllowed: "Завершені та скасовані роботи не переносяться. Оберіть активну заявку.",
    calMoveJob: "Перенести",
    calPickTime: "Оберіть час",
    calOpenCrm: "Відкрити роботу",
    calBackToCalendar: "Назад до календаря",
    calNewBooking: "+ Заявка",
    calEditBooking: "Змінити",
    calBookingCreateTitle: "Нова заявка",
    calBookingEditTitle: "Редагування заявки",
    calBookingTimeReq: "Час *",
    calBookingNameReq: "Ім'я клієнта *",
    calBookingPhoneReq: "Телефон *",
    calBookingEmail: "Електронна пошта",
    calBookingCity: "Місто",
    calBookingZip: "ZIP",
    calBookingErrEmail: "Некоректний email",
    calBookingAssignTech: "Призначити техніка",
    calBookingUnassigned: "Не призначено",
    calBookingAddress: "Адреса",
    calBookingEquipAppliance: "Обладнання",
    calBookingEquipDental: "Назва обладнання",
    calBookingProblemAppliance: "Характер поломки",
    calBookingProblemDental: "Характер несправності",
    calBookingBizType: "Тип сервісу",
    calBookingCancel: "Скасувати",
    calBookingCreateBtn: "Створити заявку",
    calBookingSaveBtn: "Зберегти",
    calBookingSaving: "Збереження…",
    calBookingErrNamePhone: "Вкажіть ім'я та телефон",
    calBookingErrSlotTaken: "Цей слот уже зайнятий",
    calBookingErrServer: "Помилка сервера",
    calBookingSavedOk: "Заявку збережено",
    calBookingNext: "Далі",
    payroll: "Зарплата",
    profile: "Профіль",
    refresh: "Оновити",
    noJobs: "Призначених робіт поки немає",
    completed: "Завершено",
    pending: "Очікує",
    confirmed: "Підтверджено",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Готово",
    paid: "Оплачено",
    cancelled: "Скасовано",
    period: "Період",
    jobsCount: "Робіт",
    gross: "Разом",
    deductions: "Відрахування",
    net: "До виплати",
    noPayroll: "Записів про зарплату поки немає",
    car: "Авто",
    plate: "Номер",
    closeJob: "Закрити роботу",
    downloadReceipt: "Завантажити чек",
    generating: "Створення...",
    repairAmount: "Сума ремонту ($)",
    workPerformed: "Виконана робота",
    workPlaceholder: "Опишіть, що було зроблено...",
    partsReplaced: "Замінені деталі",
    addPart: "+ Додати деталь",
    paymentMethod: "Спосіб оплати",
    cash: "Готівка",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Відкрити Stripe Dashboard",
    tapToPayInstruction: "Відкрийте Stripe Dashboard → створіть платіж → піднесіть картку клієнта",
    zelleInfo: "Надіслати: hitechrepairgroup@gmail.com",
    openPaymentLink: "Відкрити посилання оплати",
    online: "Онлайн (Stripe)",
    clientReceiptLang: "Мова чека клієнта",
    cancel: "Скасувати",
    followUpBtn: "Перенести / Повторний візит",
    followUpTitle: "Повторний візит",
    followUpHint: "Той самий заказ · майстер не змінюється · старий слот звільняється",
    followUpNewDate: "Нова дата",
    followUpNewTime: "Новий час",
    followUpSave: "Зберегти повторний візит",
    followUpSaving: "Збереження…",
    followUpDateTimeRequired: "Вкажіть дату і час",
    submit: "Надіслати",
    repairAmountReq: "Сума ремонту обов'язкова",
    workPerformedReq: "Опис роботи обов'язковий",
    errorClosing: "Помилка при закритті роботи",
    address: "Адреса",
    appliance: "Техніка",
    brandModel: "Марка/Модель",
    date: "Дата",
    time: "Час",
    notes: "Примітки",
    call: "Зателефонувати",
    navigate: "Маршрут",
    receiptError: "Не вдалося створити чек. Спробуйте ще раз.",
    noProfile: "Завантаження профілю...",
    sendEstimate: "Надіслати кошторис",
    estimateTitle: "Створити кошторис",
    estimateItems: "Послуги",
    addItem: "+ Додати позицію",
    itemDesc: "Опис",
    itemCat: "Категорія",
    itemQty: "К-сть",
    itemPrice: "Ціна ($)",
    estimateNotes: "Нотатки (необов'язково)",
    estimateNotesPlaceholder: "Додаткові нотатки для клієнта...",
    estimateSend: "Надіслати клієнту",
    estimateSending: "Надсилаємо...",
    estimateSuccess: "Кошторис надіслано!",
    estimateErr: "Помилка надсилання кошторису",
    noTax: "Без податку (знижка)",
    estimateSubtotal: "Підсумок",
    estimateTaxLine: "Податок (8.25%)",
    estimateTotalLine: "Разом",
    fromPricebook: "З прайс-листа",
    customItem: "Своє",
    partsCost: "Вартість деталей (факт., для звітів $)",
    partsCostHint: "Лише для внутрішнього обліку — клієнт не бачить",
    searchJobs: "Пошук: ім'я, телефон, дата, адреса…",
    searchClear: "Скинути",
    tabActive: "Активні",
    archiveJob: "В архів",
    restore: "Відновити",
    archived: "Архів",
    noArchived: "Архів порожній",
    archiving: "Архівування...",
    restoring: "Відновлення...",
    sendReview: "⭐ Запросити відгук",
    sendReviewWa: "WhatsApp",
    sendingReview: "Надсилаємо...",
    reviewSent: "Посилання на відгук надіслано!",
    notifyMethod: "Надіслати посилання на оплату через",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Обидва",
    clientContact: "Контакти клієнта",
    noContactInfo: "Контактних даних немає",
    noNotificationWillBeSent: "повідомлення не буде надіслано",
    statsClosed: "Всього закрито",
    statsRevenue: "Загальна виручка",
    statsMonth: "Цей місяць",
    statsMonthRev: "Цей місяць $",
    statsWeek: "Цей тиждень",
    statsWeekJobs: "робіт за тиждень",
    statsWeekLabor: "Робота",
    statsWeekParts: "Запчастини",
    statsWeekTax: "Податок (8.25%)",
    statsWeekNet: "Ваша частка",
    statsJobs: "робіт",
    statsTab: "Статистика",
    faceIdFailed: "Face ID не пройшов. Введіть пароль.",
    faceIdRegFailed: "Не вдалося увімкнути Face ID",
    fidEnableTitle: "Увімкнути Face ID?",
    fidEnableDesc: "Вхід одним дотиком без пароля.\nВаше обличчя / відбиток не залишає пристрій.",
    fidEnable: "Увімкнути Face ID / Відбиток",
    fidRegistering: "Реєстрація...",
    fidSkip: "Пропустити",
    fidSignIn: "Увійти через Face ID",
    fidChecking: "Перевірка...",
    fidUsePassword: "Увійти за паролем",
    photosBtn: "📷 Фото",
    photoModal: "Фото замовлення",
    photoAdd: "Зробити фото",
    photoGallery: "Обрати з галереї (до 10 фото)",
    photoLoading: "Завантаження...",
    photoNone: "Фото відсутні",
    photoDelete: "Видалити",
    photoUploadFail: "Помилка завантаження",
    sigTitle: "Підпис клієнта",
    sigClear: "Очистити",
    sigDraw: "Намалюйте підпис (опціонально)",
    sigConsentText: "Підписуючи, клієнт дозволяє HTR Dental виконати описаний ремонт. Електронний підпис дійсний за законодавством Техасу (TUETA).",
    sigOptional: "(опціонально)",
    editEmail: "Оновити Email",
    emailSaved: "Email збережено",
    emailSaveErr: "Помилка збереження Email",
    addEmail: "Додати Email",
  },
  kk: {
    title: "Техник порталы",
    phone: "Телефон",
    pin: "PIN-код",
    signIn: "Кіру",
    signingIn: "Кіруде...",
    invalidLogin: "Телефон немесе PIN қате",
    connError: "Қосылым қатесі",
    hello: "Сәлем,",
    logout: "Шығу",
    myJobs: "Менің тапсырыстарым",
    calendarTab: "Күнтізбе",
    calTitle: "Менің кестем",
    calWeek: "Апта",
    calMonth: "Ай",
    calYear: "Жыл",
    calToday: "Бүгін",
    calAllEmployees: "Барлығы",
    calNoEvents: "Бұл кезеңде жұмыс жоқ",
    calLoading: "Жүктелуде…",
    calDragHint: "Жылжыту немесе ⋮⋮ басып, жаңа күн/уақытты таңдаңыз",
    calSerial: "Серия №",
    calTechnician: "Техник",
    calOverdue: "Мерзімі өткен",
    calRescheduleOk: "Кесте жаңартылды",
    calRescheduleErr: "Қайта жоспарлау мүмкін болмады",
    calStatusCompleted: "Аяқталды",
    calStatusApproved: "Расталды",
    calStatusPending: "Күтуде",
    calBizAll: "Барлығы",
    calBizAppliance: "Техника",
    calBizDental: "Стоматология",
    calTapHint: "Күнді басыңыз. Жылжыту → толық күнтізбе ← → және «« »» (ай/жыл) + уақыт",
    calMovePickActive: "Жаңа күн немесе уақытты таңдаңыз",
    calMovePickCancel: "Болдырмау",
    calMoveNotAllowed: "Аяқталған және болдырылмаған жұмыстарды жылжытуға болмайды.",
    calMoveJob: "Жылжыту",
    calPickTime: "Уақытты таңдаңыз",
    calOpenCrm: "Тапсырысты ашу",
    calBackToCalendar: "Күнтізбеге оралу",
    calNewBooking: "+ Тапсырыс",
    calEditBooking: "Өңдеу",
    calBookingCreateTitle: "Жаңа тапсырыс",
    calBookingEditTitle: "Тапсырысты өңдеу",
    calBookingTimeReq: "Уақыт *",
    calBookingNameReq: "Клиент аты *",
    calBookingPhoneReq: "Телефон *",
    calBookingEmail: "Электрондық пошта",
    calBookingCity: "Қала",
    calBookingZip: "ZIP",
    calBookingErrEmail: "Жарамсыз email",
    calBookingAssignTech: "Техникті тағайындау",
    calBookingUnassigned: "Тағайындалмаған",
    calBookingAddress: "Мекенжай",
    calBookingEquipAppliance: "Техника / жабдық",
    calBookingEquipDental: "Жабдық атауы",
    calBookingProblemAppliance: "Мәселе сипаттамасы",
    calBookingProblemDental: "Мәселенің сипаты",
    calBookingBizType: "Қызмет түрі",
    calBookingCancel: "Болдырмау",
    calBookingCreateBtn: "Тапсырыс жасау",
    calBookingSaveBtn: "Сақтау",
    calBookingSaving: "Сақталуда…",
    calBookingErrNamePhone: "Аты мен телефон қажет",
    calBookingErrSlotTaken: "Бұл уақыт бос емес",
    calBookingErrServer: "Сервер қатесі",
    calBookingSavedOk: "Тапсырыс сақталды",
    calBookingNext: "Келесі",
    payroll: "Жалақы",
    profile: "Профиль",
    refresh: "Жаңарту",
    noJobs: "Әлі тағайындалған жұмыс жоқ",
    completed: "Аяқталды",
    pending: "Күтуде",
    confirmed: "Расталды",
    bizAppliance: "Техника",
    bizDental: "Стоматология",
    done: "Дайын",
    paid: "Төленді",
    cancelled: "Болдырылмады",
    period: "Кезең",
    jobsCount: "Жұмыстар",
    gross: "Жалпы",
    deductions: "Ұсталымдар",
    net: "Таза",
    noPayroll: "Жалақы жазбалары жоқ",
    car: "Көлік",
    plate: "Нөмір",
    closeJob: "Жұмысты жабу",
    downloadReceipt: "Түбіртек жүктеу",
    generating: "Жасалуда...",
    repairAmount: "Жөндеу сомасы ($)",
    workPerformed: "Орындалған жұмыс",
    workPlaceholder: "Не істелгенін сипаттаңыз...",
    partsReplaced: "Ауыстырылған бөлшектер",
    addPart: "+ Бөлшек қосу",
    paymentMethod: "Төлем әдісі",
    cash: "Қолма-қол",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Stripe Dashboard ашу",
    tapToPayInstruction: "Stripe Dashboard → төлем жасау → клиент картасын қою",
    zelleInfo: "Жіберу: hitechrepairgroup@gmail.com",
    openPaymentLink: "Төлем сілтемесін ашу",
    online: "Онлайн (Stripe)",
    clientReceiptLang: "Клиент түбіртегінің тілі",
    cancel: "Болдырмау",
    followUpBtn: "Қайта жоспарлау / Қайта келу",
    followUpTitle: "Қайта келу",
    followUpHint: "Сол жұмыс · тағайындау өзгермейді · ескі слот босайды",
    followUpNewDate: "Жаңа күн",
    followUpNewTime: "Жаңа уақыт",
    followUpSave: "Қайта келуді сақтау",
    followUpSaving: "Сақталуда…",
    followUpDateTimeRequired: "Күн мен уақыт қажет",
    submit: "Жіберу",
    repairAmountReq: "Жөндеу сомасы міндетті",
    workPerformedReq: "Орындалған жұмыс міндетті",
    errorClosing: "Жұмысты жабу қатесі",
    address: "Мекенжай",
    appliance: "Стоматологиялық жабдық",
    brandModel: "Бренд/Модель",
    date: "Күні",
    time: "Уақыт",
    notes: "Ескертпелер",
    call: "Қоңырау",
    smsAction: "SMS",
    emailAction: "Email",
    navigate: "Навигация",
    receiptError: "Түбіртек жасау мүмкін болмады. Қайталап көріңіз.",
    noProfile: "Профиль жүктелуде...",
    estimateSent: "Смета жіберілді",
    estimateEdit: "Өңдеу және қайта жіберу",
    estimateView: "Қарау",
    estimateDownload: "PDF",
    estimateViewError: "Сметаны ашу мүмкін болмады.",
    estimateEditTitle: "Сметаны өңдеу",
    sendEstimate: "Смета жіберу",
    estimateTitle: "Смета жасау",
    estimateItems: "Қызметтер",
    addItem: "+ Қосу",
    itemDesc: "Сипаттама",
    itemCat: "Санат",
    itemQty: "Саны",
    itemPrice: "Баға ($)",
    estimateNotes: "Ескертпелер (міндетті емес)",
    estimateNotesPlaceholder: "Клиентке қосымша ескертпелер...",
    estimateSend: "Клиентке жіберу",
    estimateSending: "Жіберілуде...",
    estimateSuccess: "Смета жіберілді!",
    estimateErr: "Смета жіберу қатесі",
    noTax: "Салықсыз (жеңілдік)",
    estimateSubtotal: "Аралық қорытынды",
    estimateTaxLine: "Салық (8.25%)",
    estimateTotalLine: "Барлығы",
    fromPricebook: "Баға тізімінен",
    customItem: "Басқа",
    partsCost: "Бөлшектер құны (ішкі, есептерге $)",
    partsCostHint: "Тек ішкі — клиентке көрсетілмейді",
    searchJobs: "Аты, телефон, күн, мекенжай бойынша іздеу…",
    searchClear: "Тазалау",
    tabActive: "Белсенді",
    archiveJob: "Мұрағатқа",
    restore: "Қалпына келтіру",
    archived: "Мұрағатталған",
    noArchived: "Мұрағатта жұмыс жоқ",
    archiving: "Мұрағатталуда...",
    restoring: "Қалпына келтірілуде...",
    sendReview: "⭐ Пікір сұрау",
    sendReviewWa: "WhatsApp",
    sendingReview: "Жіберілуде...",
    reviewSent: "Пікір сілтемесі жіберілді!",
    notifyMethod: "Төлем сілтемесін жіберу",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Екеуі де",
    clientContact: "Клиент байланысы",
    noContactInfo: "Байланыс деректері жоқ",
    noNotificationWillBeSent: "хабарлама жіберілмейді",
    statsClosed: "Жабылғандар",
    statsRevenue: "Жалпы түсім",
    statsMonth: "Осы ай",
    statsMonthRev: "Осы ай $",
    statsWeek: "Осы апта",
    statsWeekJobs: "аптадағы жұмыстар",
    statsWeekLabor: "Еңбек",
    statsWeekParts: "Бөлшектер",
    statsWeekTax: "Салық (8.25%)",
    statsWeekNet: "Сіздің таза табысыңыз",
    statsJobs: "жұмыс",
    statsTab: "Статистика",
    faceIdFailed: "Face ID сәтсіз. Құпия сөзді енгізіңіз.",
    faceIdRegFailed: "Face ID қосу мүмкін болмады",
    fidEnableTitle: "Face ID қосу керек пе?",
    fidEnableDesc: "Бір басумен кіріңіз, құпия сөзсіз.\nБет / саусақ ізі құрылғыдан шықпайды.",
    fidEnable: "Face ID / Саусақ ізі қосу",
    fidRegistering: "Тіркелуде...",
    fidSkip: "Өткізу",
    fidSignIn: "Face ID арқылы кіру",
    fidChecking: "Тексерілуде...",
    fidUsePassword: "Құпия сөзбен кіру",
    photosBtn: "📷 Фото",
    photoModal: "Жұмыс фотолары",
    photoAdd: "Фото түсіру",
    photoGallery: "Галереядан таңдау (10-ға дейін)",
    photoLoading: "Жүктелуде...",
    photoNone: "Фото жоқ",
    photoDelete: "Жою",
    photoUploadFail: "Жүктеу сәтсіз",
    sigTitle: "Клиент қолтаңбасы",
    sigClear: "Тазалау",
    sigDraw: "Осында қол қойыңыз (міндетті емес)",
    sigConsentText: "Қол қою арқылы клиент HTR Dental-ға сипатталған жөндеуді рұқсат етеді. Электрондық қолтаңба Техас заңы бойынша жарамды (TUETA).",
    sigOptional: "(міндетті емес)",
    editEmail: "Email өңдеу",
    emailSaved: "Email сақталды",
    emailSaveErr: "Email сақтау қатесі",
    addEmail: "Email қосу",
  },
  ky: {
    title: "Техник порталы",
    phone: "Телефон",
    pin: "PIN-код",
    signIn: "Кирүү",
    signingIn: "Кирүүдө...",
    invalidLogin: "Телефон же PIN туура эмес",
    connError: "Байланыш катасы",
    hello: "Салам,",
    logout: "Чыгуу",
    myJobs: "Менин буйрутмаларым",
    calendarTab: "Жылнаама",
    calTitle: "Менин графигим",
    calWeek: "Апта",
    calMonth: "Ай",
    calYear: "Жыл",
    calToday: "Бүгүн",
    calAllEmployees: "Баары",
    calNoEvents: "Бул мезгилде жумуш жок",
    calLoading: "Жүктөлүүдө…",
    calDragHint: "Жылдыруу же ⋮⋮ басып, жаңы күн/убакытты тандаңыз",
    calSerial: "Серия №",
    calTechnician: "Техник",
    calOverdue: "Мөөнөтү өткөн",
    calRescheduleOk: "График жаңыртылды",
    calRescheduleErr: "Кайра пландаштыруу мүмкүн болбоду",
    calStatusCompleted: "Аякталды",
    calStatusApproved: "Ырасталды",
    calStatusPending: "Күтүүдө",
    calBizAll: "Баары",
    calBizAppliance: "Техника",
    calBizDental: "Стоматология",
    calTapHint: "Күндү басыңыз. Жылдыруу → толук жылнаама ← → жана «« »» (ай/жыл) + убакыт",
    calMovePickActive: "Жаңы күн же убакытты тандаңыз",
    calMovePickCancel: "Жокко чыгаруу",
    calMoveNotAllowed: "Аякталган жана жокко чыгарылган жумуштарды жылдырууга болбойт.",
    calMoveJob: "Жылдыруу",
    calPickTime: "Убакытты тандаңыз",
    calOpenCrm: "Буйрутманы ачуу",
    calBackToCalendar: "Жылнаамага кайтуу",
    calNewBooking: "+ Буйрутма",
    calEditBooking: "Оңдоо",
    calBookingCreateTitle: "Жаңы буйрутма",
    calBookingEditTitle: "Буйрутманы оңдоо",
    calBookingTimeReq: "Убакыт *",
    calBookingNameReq: "Кардардын аты *",
    calBookingPhoneReq: "Телефон *",
    calBookingEmail: "Электрондук почта",
    calBookingCity: "Шаар",
    calBookingZip: "ZIP",
    calBookingErrEmail: "Туура эмес email",
    calBookingAssignTech: "Техникти дайындоо",
    calBookingUnassigned: "Дайындалган эмес",
    calBookingAddress: "Дарек",
    calBookingEquipAppliance: "Техника / жабдуу",
    calBookingEquipDental: "Жабдуунун аталышы",
    calBookingProblemAppliance: "Маселенин сүрөттөмөсү",
    calBookingProblemDental: "Маселенин мүнөзү",
    calBookingBizType: "Кызмат түрү",
    calBookingCancel: "Жокко чыгаруу",
    calBookingCreateBtn: "Буйрутма түзүү",
    calBookingSaveBtn: "Сактоо",
    calBookingSaving: "Сакталууда…",
    calBookingErrNamePhone: "Аты жана телефон керек",
    calBookingErrSlotTaken: "Бул убакыт бош эмес",
    calBookingErrServer: "Сервер катасы",
    calBookingSavedOk: "Буйрутма сакталды",
    calBookingNext: "Кийинки",
    payroll: "Эмгек акы",
    profile: "Профиль",
    refresh: "Жаңыртуу",
    noJobs: "Дагы дайындалган жумуш жок",
    completed: "Аякталды",
    pending: "Күтүүдө",
    confirmed: "Ырасталды",
    bizAppliance: "Техника",
    bizDental: "Стоматология",
    done: "Даяр",
    paid: "Төлөндү",
    cancelled: "Жокко чыгарылды",
    period: "Мезгил",
    jobsCount: "Жумуштар",
    gross: "Жалпы",
    deductions: "Кармап калуулар",
    net: "Таза",
    noPayroll: "Эмгек акы жазуулары жок",
    car: "Унаа",
    plate: "Номер",
    closeJob: "Жумушту жабуу",
    downloadReceipt: "Дүмүрчөктү жүктөө",
    generating: "Түзүлүүдө...",
    repairAmount: "Оңдоо суммасы ($)",
    workPerformed: "Аткарылган жумуш",
    workPlaceholder: "Эмне кылынганын сүрөттөңүз...",
    partsReplaced: "Алмаштырылган тетиктер",
    addPart: "+ Тетик кошуу",
    paymentMethod: "Төлөм ыкмасы",
    cash: "Накталай",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Stripe Dashboard ачуу",
    tapToPayInstruction: "Stripe Dashboard → төлөм түзүү → кардардын картасын коюу",
    zelleInfo: "Жөнөтүү: hitechrepairgroup@gmail.com",
    openPaymentLink: "Төлөм шилтемесин ачуу",
    online: "Онлайн (Stripe)",
    clientReceiptLang: "Кардар дүмүрчөгүнүн тили",
    cancel: "Жокко чыгаруу",
    followUpBtn: "Кайра пландаштыруу / Кайталоо",
    followUpTitle: "Кайталоо визити",
    followUpHint: "Ошол эле жумуш · дайындоо өзгөрбөйт · эски слот бошойт",
    followUpNewDate: "Жаңы күн",
    followUpNewTime: "Жаңы убакыт",
    followUpSave: "Кайталоону сактоо",
    followUpSaving: "Сакталууда…",
    followUpDateTimeRequired: "Күн жана убакыт керек",
    submit: "Жөнөтүү",
    repairAmountReq: "Оңдоо суммасы милдеттүү",
    workPerformedReq: "Аткарылган жумуш милдеттүү",
    errorClosing: "Жумушту жабуу катасы",
    address: "Дарек",
    appliance: "Стоматологиялык жабдуу",
    brandModel: "Бренд/Модель",
    date: "Күнү",
    time: "Убакыт",
    notes: "Эскертүүлөр",
    call: "Чалуу",
    smsAction: "SMS",
    emailAction: "Email",
    navigate: "Навигация",
    receiptError: "Дүмүрчөк түзүлбөдү. Кайра аракет кылыңыз.",
    noProfile: "Профиль жүктөлүүдө...",
    estimateSent: "Смета жөнөтүлдү",
    estimateEdit: "Оңдоо жана кайра жөнөтүү",
    estimateView: "Көрүү",
    estimateDownload: "PDF",
    estimateViewError: "Сметаны ачуу мүмкүн болбоду.",
    estimateEditTitle: "Сметаны оңдоо",
    sendEstimate: "Смета жөнөтүү",
    estimateTitle: "Смета түзүү",
    estimateItems: "Кызматтар",
    addItem: "+ Кошуу",
    itemDesc: "Сүрөттөмө",
    itemCat: "Категория",
    itemQty: "Саны",
    itemPrice: "Баа ($)",
    estimateNotes: "Эскертүүлөр (милдеттүү эмес)",
    estimateNotesPlaceholder: "Кардарга кошумча эскертүүлөр...",
    estimateSend: "Кардарга жөнөтүү",
    estimateSending: "Жөнөтүлүүдө...",
    estimateSuccess: "Смета жөнөтүлдү!",
    estimateErr: "Смета жөнөтүү катасы",
    noTax: "Салыксыз (арзандатуу)",
    estimateSubtotal: "Аралык жыйынтык",
    estimateTaxLine: "Салык (8.25%)",
    estimateTotalLine: "Жалпы",
    fromPricebook: "Баа тизмесинен",
    customItem: "Башка",
    partsCost: "Тетиктердин баасы (ички, отчетторго $)",
    partsCostHint: "Ички гана — кардарга көрсөтүлбөйт",
    searchJobs: "Аты, телефон, күн, дарек боюнча издөө…",
    searchClear: "Тазалоо",
    tabActive: "Активдүү",
    archiveJob: "Архивге",
    restore: "Калыбына келтирүү",
    archived: "Архивделген",
    noArchived: "Архивде жумуш жок",
    archiving: "Архивделип жатат...",
    restoring: "Калыбына келтирилүүдө...",
    sendReview: "⭐ Пикир суроо",
    sendReviewWa: "WhatsApp",
    sendingReview: "Жөнөтүлүүдө...",
    reviewSent: "Пикир шилтемеси жөнөтүлдү!",
    notifyMethod: "Төлөм шилтемесин жөнөтүү",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Экөө тең",
    clientContact: "Кардар байланышы",
    noContactInfo: "Байланыш маалыматы жок",
    noNotificationWillBeSent: "билдирүү жөнөтүлбөйт",
    statsClosed: "Жабылгандар",
    statsRevenue: "Жалпы киреше",
    statsMonth: "Ушул ай",
    statsMonthRev: "Ушул ай $",
    statsWeek: "Ушул апта",
    statsWeekJobs: "аптадагы жумуштар",
    statsWeekLabor: "Эмгек",
    statsWeekParts: "Тетиктер",
    statsWeekTax: "Салык (8.25%)",
    statsWeekNet: "Сиздин таза кирешеңиз",
    statsJobs: "жумуш",
    statsTab: "Статистика",
    faceIdFailed: "Face ID ийгиликсиз. Сырсөздү киргизиңиз.",
    faceIdRegFailed: "Face ID күйгүзүлбөдү",
    fidEnableTitle: "Face ID күйгүзүлсүнбү?",
    fidEnableDesc: "Бир басуу менен кириңиз, сырсөзсүз.\nБет / манжа изи түзмөктөн чыкпайт.",
    fidEnable: "Face ID / Манжа изин күйгүзүү",
    fidRegistering: "Катталууда...",
    fidSkip: "Өткөрүп жиберүү",
    fidSignIn: "Face ID менен кирүү",
    fidChecking: "Текшерилүүдө...",
    fidUsePassword: "Сырсөз менен кирүү",
    photosBtn: "📷 Сүрөт",
    photoModal: "Жумуш сүрөттөрү",
    photoAdd: "Сүрөткө тартуу",
    photoGallery: "Галереядан тандоо (10го чейин)",
    photoLoading: "Жүктөлүүдө...",
    photoNone: "Сүрөт жок",
    photoDelete: "Өчүрүү",
    photoUploadFail: "Жүктөө ийгиликсиз",
    sigTitle: "Кардардын колу",
    sigClear: "Тазалоо",
    sigDraw: "Бул жерге кол коюңуз (милдеттүү эмес)",
    sigConsentText: "Кол коюу менен кардар HTR Dentalга сүрөттөлгөн оңдоону уруксат кылат. Электрондук кол Техас мыйзамы боюнча жарактуу (TUETA).",
    sigOptional: "(милдеттүү эмес)",
    editEmail: "Email оңдоо",
    emailSaved: "Email сакталды",
    emailSaveErr: "Email сактоо катасы",
    addEmail: "Email кошуу",
  },
  uz: {
    title: "Texnik portali",
    phone: "Telefon",
    pin: "PIN-kod",
    signIn: "Kirish",
    signingIn: "Kirilmoqda...",
    invalidLogin: "Telefon yoki PIN noto‘g‘ri",
    connError: "Ulanish xatosi",
    hello: "Salom,",
    logout: "Chiqish",
    myJobs: "Mening buyurtmalarim",
    calendarTab: "Kalendar",
    calTitle: "Mening jadvalim",
    calWeek: "Hafta",
    calMonth: "Oy",
    calYear: "Yil",
    calToday: "Bugun",
    calAllEmployees: "Hammasi",
    calNoEvents: "Bu davrda ish yo‘q",
    calLoading: "Yuklanmoqda…",
    calDragHint: "Ko‘chirish yoki ⋮⋮ bosing, keyin yangi kun/vaqtni tanlang",
    calSerial: "Seriya №",
    calTechnician: "Texnik",
    calOverdue: "Muddati o‘tgan",
    calRescheduleOk: "Jadval yangilandi",
    calRescheduleErr: "Qayta rejalashtirish imkonsiz",
    calStatusCompleted: "Yakunlandi",
    calStatusApproved: "Tasdiqlangan",
    calStatusPending: "Kutilmoqda",
    calBizAll: "Hammasi",
    calBizAppliance: "Texnika",
    calBizDental: "Stomatologiya",
    calTapHint: "Kunni bosing. Ko‘chirish → to‘liq kalendar ← → va «« »» (oy/yil) + vaqt",
    calMovePickActive: "Yangi kun yoki vaqtni tanlang",
    calMovePickCancel: "Bekor qilish",
    calMoveNotAllowed: "Yakunlangan va bekor qilingan ishlarni ko‘chirib bo‘lmaydi.",
    calMoveJob: "Ko‘chirish",
    calPickTime: "Vaqtni tanlang",
    calOpenCrm: "Buyurtmani ochish",
    calBackToCalendar: "Kalendarga qaytish",
    calNewBooking: "+ Buyurtma",
    calEditBooking: "Tahrirlash",
    calBookingCreateTitle: "Yangi buyurtma",
    calBookingEditTitle: "Buyurtmani tahrirlash",
    calBookingTimeReq: "Vaqt *",
    calBookingNameReq: "Mijoz ismi *",
    calBookingPhoneReq: "Telefon *",
    calBookingEmail: "Elektron pochta",
    calBookingCity: "Shahar",
    calBookingZip: "ZIP",
    calBookingErrEmail: "Noto‘g‘ri email",
    calBookingAssignTech: "Texnikni biriktirish",
    calBookingUnassigned: "Biriktirilmagan",
    calBookingAddress: "Manzil",
    calBookingEquipAppliance: "Texnika / jihoz",
    calBookingEquipDental: "Jihoz nomi",
    calBookingProblemAppliance: "Muammo tavsifi",
    calBookingProblemDental: "Muammo xususiyati",
    calBookingBizType: "Xizmat turi",
    calBookingCancel: "Bekor qilish",
    calBookingCreateBtn: "Buyurtma yaratish",
    calBookingSaveBtn: "Saqlash",
    calBookingSaving: "Saqlanmoqda…",
    calBookingErrNamePhone: "Ism va telefon kerak",
    calBookingErrSlotTaken: "Bu vaqt band",
    calBookingErrServer: "Server xatosi",
    calBookingSavedOk: "Buyurtma saqlandi",
    calBookingNext: "Keyingi",
    payroll: "Ish haqi",
    profile: "Profil",
    refresh: "Yangilash",
    noJobs: "Hali tayinlangan ish yo‘q",
    completed: "Yakunlandi",
    pending: "Kutilmoqda",
    confirmed: "Tasdiqlangan",
    bizAppliance: "Texnika",
    bizDental: "Stomatologiya",
    done: "Tayyor",
    paid: "To‘langan",
    cancelled: "Bekor qilingan",
    period: "Davr",
    jobsCount: "Ishlar",
    gross: "Umumiy",
    deductions: "Ushlab qolishlar",
    net: "Sof",
    noPayroll: "Ish haqi yozuvlari yo‘q",
    car: "Avtomobil",
    plate: "Raqam",
    closeJob: "Ishni yopish",
    downloadReceipt: "Kvitansiyani yuklash",
    generating: "Yaratilmoqda...",
    repairAmount: "Ta’mirlash summasi ($)",
    workPerformed: "Bajarilgan ish",
    workPlaceholder: "Nima qilinganini tavsiflang...",
    partsReplaced: "Almashtirilgan qismlar",
    addPart: "+ Qism qo‘shish",
    paymentMethod: "To‘lov usuli",
    cash: "Naqd",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Stripe Dashboard ochish",
    tapToPayInstruction: "Stripe Dashboard → to‘lov yaratish → mijoz kartasini qo‘ying",
    zelleInfo: "Yuborish: hitechrepairgroup@gmail.com",
    openPaymentLink: "To‘lov havolasini ochish",
    online: "Onlayn (Stripe)",
    clientReceiptLang: "Mijoz kvitansiyasi tili",
    cancel: "Bekor qilish",
    followUpBtn: "Qayta rejalashtirish / Takroriy tashrif",
    followUpTitle: "Takroriy tashrif",
    followUpHint: "Xuddi shu ish · tayinlash o‘zgarmaydi · eski slot bo‘shaydi",
    followUpNewDate: "Yangi sana",
    followUpNewTime: "Yangi vaqt",
    followUpSave: "Takroriy tashrifni saqlash",
    followUpSaving: "Saqlanmoqda…",
    followUpDateTimeRequired: "Sana va vaqt kerak",
    submit: "Yuborish",
    repairAmountReq: "Ta’mirlash summasi majburiy",
    workPerformedReq: "Bajarilgan ish majburiy",
    errorClosing: "Ishni yopish xatosi",
    address: "Manzil",
    appliance: "Stomatologiya jihozi",
    brandModel: "Brend/Model",
    date: "Sana",
    time: "Vaqt",
    notes: "Izohlar",
    call: "Qo‘ng‘iroq",
    smsAction: "SMS",
    emailAction: "Email",
    navigate: "Navigatsiya",
    receiptError: "Kvitansiya yaratilmadi. Qayta urinib ko‘ring.",
    noProfile: "Profil yuklanmoqda...",
    estimateSent: "Smeta yuborildi",
    estimateEdit: "Tahrirlash va qayta yuborish",
    estimateView: "Ko‘rish",
    estimateDownload: "PDF",
    estimateViewError: "Smetani ochib bo‘lmadi.",
    estimateEditTitle: "Smetani tahrirlash",
    sendEstimate: "Smeta yuborish",
    estimateTitle: "Smeta yaratish",
    estimateItems: "Xizmatlar",
    addItem: "+ Qo‘shish",
    itemDesc: "Tavsif",
    itemCat: "Kategoriya",
    itemQty: "Soni",
    itemPrice: "Narx ($)",
    estimateNotes: "Izohlar (ixtiyoriy)",
    estimateNotesPlaceholder: "Mijoz uchun qo‘shimcha izohlar...",
    estimateSend: "Mijozga yuborish",
    estimateSending: "Yuborilmoqda...",
    estimateSuccess: "Smeta yuborildi!",
    estimateErr: "Smeta yuborish xatosi",
    noTax: "Soliqsiz (chegirma)",
    estimateSubtotal: "Oraliq jami",
    estimateTaxLine: "Soliq (8.25%)",
    estimateTotalLine: "Jami",
    fromPricebook: "Narxlar ro‘yxatidan",
    customItem: "Boshqa",
    partsCost: "Qismlar narxi (ichki, hisobotlar uchun $)",
    partsCostHint: "Faqat ichki — mijozga ko‘rsatilmaydi",
    searchJobs: "Ism, telefon, sana, manzil bo‘yicha qidirish…",
    searchClear: "Tozalash",
    tabActive: "Faol",
    archiveJob: "Arxivga",
    restore: "Tiklash",
    archived: "Arxivlangan",
    noArchived: "Arxivda ish yo‘q",
    archiving: "Arxivlanmoqda...",
    restoring: "Tiklanmoqda...",
    sendReview: "⭐ Sharh so‘rash",
    sendReviewWa: "WhatsApp",
    sendingReview: "Yuborilmoqda...",
    reviewSent: "Sharh havolasi yuborildi!",
    notifyMethod: "To‘lov havolasini yuborish",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Ikkalasi",
    clientContact: "Mijoz aloqasi",
    noContactInfo: "Aloqa ma’lumoti yo‘q",
    noNotificationWillBeSent: "xabar yuborilmaydi",
    statsClosed: "Yopilganlar",
    statsRevenue: "Umumiy daromad",
    statsMonth: "Shu oy",
    statsMonthRev: "Shu oy $",
    statsWeek: "Shu hafta",
    statsWeekJobs: "haftadagi ishlar",
    statsWeekLabor: "Mehnat",
    statsWeekParts: "Qismlar",
    statsWeekTax: "Soliq (8.25%)",
    statsWeekNet: "Sizning sof daromadingiz",
    statsJobs: "ish",
    statsTab: "Statistika",
    faceIdFailed: "Face ID muvaffaqiyatsiz. Parolni kiriting.",
    faceIdRegFailed: "Face ID yoqilmadi",
    fidEnableTitle: "Face ID yoqilsinmi?",
    fidEnableDesc: "Bir bosishda kiring, parolsiz.\nYuz / barmoq izi qurilmadan chiqmaydi.",
    fidEnable: "Face ID / Barmoq izini yoqish",
    fidRegistering: "Ro‘yxatdan o‘tmoqda...",
    fidSkip: "O‘tkazib yuborish",
    fidSignIn: "Face ID bilan kirish",
    fidChecking: "Tekshirilmoqda...",
    fidUsePassword: "Parol bilan kirish",
    photosBtn: "📷 Foto",
    photoModal: "Ish fotolari",
    photoAdd: "Foto olish",
    photoGallery: "Galereyadan tanlash (10 gacha)",
    photoLoading: "Yuklanmoqda...",
    photoNone: "Foto yo‘q",
    photoDelete: "O‘chirish",
    photoUploadFail: "Yuklash muvaffaqiyatsiz",
    sigTitle: "Mijoz imzosi",
    sigClear: "Tozalash",
    sigDraw: "Bu yerga imzo qo‘ying (ixtiyoriy)",
    sigConsentText: "Imzo qo‘yib, mijoz HTR Dentalga tavsiflangan ta’mirlashni ruxsat qiladi. Elektron imzo Texas qonuni bo‘yicha amal qiladi (TUETA).",
    sigOptional: "(ixtiyoriy)",
    editEmail: "Email tahrirlash",
    emailSaved: "Email saqlandi",
    emailSaveErr: "Email saqlash xatosi",
    addEmail: "Email qo‘shish",
  },
};

interface EmpLangContextType {
  lang: EmpLang;
  setLang: (lang: EmpLang) => void;
  t: (key: string) => string;
}

const EmpLangContext = createContext<EmpLangContextType | undefined>(undefined);

const EMP_LANG_CODES: EmpLang[] = ["en", "ru", "es", "tr", "az", "uk", "kk", "ky", "uz"];

function readEmpLang(): EmpLang {
  try {
    const saved = localStorage.getItem("empUiLang");
    if (saved && (EMP_LANG_CODES as string[]).includes(saved)) return saved as EmpLang;
  } catch { /* ignore */ }
  return "en";
}

export function EmpLangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<EmpLang>(() => readEmpLang());

  const setLang = useCallback((newLang: EmpLang) => {
    setLangState(newLang);
    try { localStorage.setItem("empUiLang", newLang); } catch { /* ignore */ }
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang]?.[key] ?? translations.en[key] ?? key;
  }, [lang]);

  return (
    <EmpLangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </EmpLangContext.Provider>
  );
}

export function useEmpLang() {
  const context = useContext(EmpLangContext);
  if (!context) throw new Error("useEmpLang must be used within EmpLangProvider");
  return context;
}
