import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from "react";

export type EmpLang = "en" | "ru" | "es" | "tr" | "az" | "uk";

export const translations: Record<EmpLang, Record<string, string>> = {
  en: {
    title: "Technician Dashboard",
    phone: "Phone",
    pin: "PIN",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalidLogin: "Invalid phone or PIN",
    connError: "Connection error",
    hello: "Hello,",
    logout: "Logout",
    myJobs: "Dental Service Jobs",
    calendarTab: "Calendar",
    calTitle: "My Schedule",
    calWeek: "Week",
    calMonth: "Month",
    calYear: "Year",
    calToday: "Today",
    calAllEmployees: "All",
    calNoEvents: "No jobs in this period",
    calLoading: "Loading…",
    calDragHint: "Drag a job onto a day number in the calendar",
    calSerial: "Serial #",
    calTechnician: "Technician",
    calOverdue: "Overdue",
    calRescheduleOk: "Schedule updated",
    calRescheduleErr: "Could not reschedule",
    calStatusCompleted: "Completed",
    calStatusApproved: "Confirmed",
    calStatusPending: "Pending",
    calBizAll: "All",
    calBizAppliance: "Appliance",
    calBizDental: "Dental",
    calTapHint: "Tap a day — drag a job to another day number",
    calMoveJob: "Move",
    calPickTime: "Pick a time",
    calOpenCrm: "Open job",
    calBackToCalendar: "Back to calendar",
    calNewBooking: "+ Booking",
    calEditBooking: "Edit",
    calBookingCreateTitle: "New booking",
    calBookingEditTitle: "Edit booking",
    calBookingTimeReq: "Time *",
    calBookingNameReq: "Client name *",
    calBookingPhoneReq: "Phone *",
    calBookingAddress: "Address",
    calBookingEquipAppliance: "Appliance / equipment",
    calBookingEquipDental: "Equipment name",
    calBookingProblemAppliance: "Issue description",
    calBookingProblemDental: "Nature of the problem",
    calBookingBizType: "Service type",
    calBookingCancel: "Cancel",
    calBookingCreateBtn: "Create booking",
    calBookingSaveBtn: "Save",
    calBookingSaving: "Saving…",
    calBookingErrNamePhone: "Name and phone required",
    calBookingErrSlotTaken: "This time slot is already taken",
    calBookingErrServer: "Server error",
    calBookingSavedOk: "Booking saved",
    calBookingNext: "Next",
    payroll: "Payroll",
    profile: "Profile",
    refresh: "Refresh",
    noJobs: "No assigned jobs yet",
    completed: "Completed",
    pending: "Pending",
    confirmed: "Confirmed",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Done",
    paid: "Paid",
    cancelled: "Cancelled",
    period: "Period",
    jobsCount: "Jobs",
    gross: "Gross",
    deductions: "Deductions",
    net: "Net",
    noPayroll: "No payroll records yet",
    car: "Car",
    plate: "Plate",
    closeJob: "Close Job",
    downloadReceipt: "Download Receipt",
    generating: "Generating...",
    repairAmount: "Repair Amount ($)",
    workPerformed: "Work Performed",
    workPlaceholder: "Describe what was done...",
    partsReplaced: "Parts Replaced",
    addPart: "+ Add Part",
    paymentMethod: "Payment Method",
    cash: "Cash",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Open Stripe Dashboard",
    tapToPayInstruction: "Open the Stripe Dashboard app → create a payment → tap client's card",
    zelleInfo: "Send to: htrgroupllc@gmail.com",
    openPaymentLink: "Open Payment Link",
    online: "Online (Stripe)",
    clientReceiptLang: "Client Receipt Language",
    cancel: "Cancel",
    submit: "Submit",
    repairAmountReq: "Repair Amount is required",
    workPerformedReq: "Work Performed is required",
    errorClosing: "Error closing job",
    address: "Address",
    appliance: "Dental Equipment",
    brandModel: "Brand/Model",
    date: "Date",
    time: "Time",
    notes: "Notes",
    call: "Call",
    smsAction: "SMS",
    emailAction: "Email",
    navigate: "Navigate",
    receiptError: "Could not generate receipt. Please try again.",
    noProfile: "Loading profile...",
    estimateSent: "Estimate sent",
    estimateEdit: "Edit & Resend",
    estimateView: "View",
    estimateDownload: "PDF",
    estimateViewError: "Could not open estimate. Please try again.",
    estimateEditTitle: "Edit Estimate",
    sendEstimate: "Send Estimate",
    estimateTitle: "Create Estimate",
    estimateItems: "Service Items",
    addItem: "+ Add Item",
    itemDesc: "Description",
    itemCat: "Category",
    itemQty: "Qty",
    itemPrice: "Price ($)",
    estimateNotes: "Notes (optional)",
    estimateNotesPlaceholder: "Additional notes for the client...",
    estimateSend: "Send to Client",
    estimateSending: "Sending...",
    estimateSuccess: "Estimate sent!",
    estimateErr: "Error sending estimate",
    noTax: "No tax (discount)",
    estimateSubtotal: "Subtotal",
    estimateTaxLine: "Tax (8.25%)",
    estimateTotalLine: "Total",
    fromPricebook: "From Pricebook",
    customItem: "Custom",
    partsCost: "Parts Cost (actual, for reports $)",
    partsCostHint: "Internal only — not shown to client",
    searchJobs: "Search by name, phone, date, address…",
    searchClear: "Clear",
    tabActive: "Active",
    archiveJob: "Move to Archive",
    restore: "Restore",
    archived: "Archived",
    noArchived: "No archived jobs",
    archiving: "Archiving...",
    restoring: "Restoring...",
    sendReview: "⭐ Request Review",
    sendReviewWa: "WhatsApp",
    sendingReview: "Sending...",
    reviewSent: "Review link sent!",
    notifyMethod: "Send Payment Link Via",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Both",
    clientContact: "Client Contact",
    noContactInfo: "No contact info on file",
    noNotificationWillBeSent: "no notification will be sent",
    statsClosed: "Total Closed",
    statsRevenue: "Total Revenue",
    statsMonth: "This Month",
    statsMonthRev: "This Month $",
    statsWeek: "This Week",
    statsWeekJobs: "jobs this week",
    statsWeekLabor: "Labor",
    statsWeekParts: "Parts",
    statsWeekTax: "Tax (8.25%)",
    statsWeekNet: "Your net",
    statsJobs: "jobs",
    statsTab: "Stats",
    faceIdFailed: "Face ID failed. Enter password.",
    faceIdRegFailed: "Could not enable Face ID",
    fidEnableTitle: "Enable Face ID?",
    fidEnableDesc: "Sign in with one touch, no password needed.\nYour face / fingerprint never leaves your device.",
    fidEnable: "Enable Face ID / Fingerprint",
    fidRegistering: "Registering...",
    fidSkip: "Skip",
    fidSignIn: "Sign in with Face ID",
    fidChecking: "Checking...",
    fidUsePassword: "Sign in with password",
    photosBtn: "📷 Photos",
    photoModal: "Job Photos",
    photoAdd: "Take Photo",
    photoGallery: "Choose from Gallery (up to 10)",
    photoLoading: "Loading...",
    photoNone: "No photos yet",
    photoDelete: "Delete",
    photoUploadFail: "Upload failed",
    sigTitle: "Client Signature",
    sigClear: "Clear",
    sigDraw: "Sign here (optional)",
    sigConsentText: "By signing, the client authorizes HTR Dental to perform the described repairs. Electronic signature valid under Texas law (TUETA).",
    sigOptional: "(optional)",
    editEmail: "Edit Email",
    emailSaved: "Email saved",
    emailSaveErr: "Error saving email",
    addEmail: "Add Email",
  },
  ru: {
    title: "Портал сотрудника",
    phone: "Телефон",
    pin: "ПИН-код",
    signIn: "Войти",
    signingIn: "Вход...",
    invalidLogin: "Неверный телефон или ПИН",
    connError: "Ошибка соединения",
    hello: "Привет,",
    logout: "Выйти",
    myJobs: "Мои заказы",
    calendarTab: "Календарь",
    calTitle: "Моё расписание",
    calWeek: "Неделя",
    calMonth: "Месяц",
    calYear: "Год",
    calToday: "Сегодня",
    calAllEmployees: "Все",
    calNoEvents: "Нет заказов в этом периоде",
    calLoading: "Загрузка…",
    calDragHint: "Перетащите заказ для переноса (неделя)",
    calSerial: "Серийный №",
    calTechnician: "Техник",
    calOverdue: "Просрочен",
    calRescheduleOk: "Время обновлено",
    calRescheduleErr: "Не удалось перенести",
    calStatusCompleted: "Завершён",
    calStatusApproved: "Подтверждён",
    calStatusPending: "Ожидает",
    calBizAll: "Все",
    calBizAppliance: "Appliance",
    calBizDental: "Dental",
    calTapHint: "Нажмите на заказ — перенос через «Перенести»",
    calMoveJob: "Перенести",
    calPickTime: "Выберите время",
    calOpenCrm: "Открыть заказ",
    calBackToCalendar: "Назад к календарю",
    calNewBooking: "+ Заявка",
    calEditBooking: "Изменить",
    calBookingCreateTitle: "Новая заявка",
    calBookingEditTitle: "Редактирование заявки",
    calBookingTimeReq: "Время *",
    calBookingNameReq: "Имя клиента *",
    calBookingPhoneReq: "Телефон *",
    calBookingAddress: "Адрес",
    calBookingEquipAppliance: "Оборудование",
    calBookingEquipDental: "Наименование оборудования",
    calBookingProblemAppliance: "Характер поломки",
    calBookingProblemDental: "Характер неисправности",
    calBookingBizType: "Тип сервиса",
    calBookingCancel: "Отмена",
    calBookingCreateBtn: "Создать заявку",
    calBookingSaveBtn: "Сохранить",
    calBookingSaving: "Сохранение…",
    calBookingErrNamePhone: "Укажите имя и телефон",
    calBookingErrSlotTaken: "Этот слот уже занят",
    calBookingErrServer: "Ошибка сервера",
    calBookingSavedOk: "Заявка сохранена",
    calBookingNext: "Далее",
    payroll: "Зарплата",
    profile: "Профиль",
    refresh: "Обновить",
    noJobs: "Назначенных заказов пока нет",
    completed: "Завершено",
    pending: "Ожидает",
    confirmed: "Подтверждено",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Готово",
    paid: "Оплачено",
    cancelled: "Отменено",
    period: "Период",
    jobsCount: "Заказов",
    gross: "Всего",
    deductions: "Вычеты",
    net: "К выплате",
    noPayroll: "Записей о зарплате пока нет",
    car: "Авто",
    plate: "Номер",
    closeJob: "Закрыть заказ",
    downloadReceipt: "Скачать чек",
    generating: "Создание...",
    repairAmount: "Сумма ремонта ($)",
    workPerformed: "Выполненная работа",
    workPlaceholder: "Опишите, что было сделано...",
    partsReplaced: "Замененные детали",
    addPart: "+ Добавить деталь",
    paymentMethod: "Способ оплаты",
    cash: "Наличные",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Открыть Stripe Dashboard",
    tapToPayInstruction: "Откройте Stripe Dashboard → создайте платёж → поднесите карту клиента",
    zelleInfo: "Отправить: htrgroupllc@gmail.com",
    openPaymentLink: "Открыть ссылку оплаты",
    online: "Онлайн (Stripe)",
    clientReceiptLang: "Язык чека клиента",
    cancel: "Отмена",
    submit: "Отправить",
    repairAmountReq: "Сумма ремонта обязательна",
    workPerformedReq: "Описание работы обязательно",
    errorClosing: "Ошибка при закрытии заказа",
    address: "Адрес",
    appliance: "Техника",
    brandModel: "Марка/Модель",
    date: "Дата",
    time: "Время",
    notes: "Заметки",
    call: "Позвонить",
    smsAction: "SMS",
    emailAction: "Email",
    navigate: "Маршрут",
    receiptError: "Не удалось создать чек. Попробуйте еще раз.",
    noProfile: "Загрузка профиля...",
    estimateSent: "Смета отправлена",
    estimateEdit: "Изменить и отправить",
    estimateView: "Просмотр",
    estimateDownload: "PDF",
    estimateViewError: "Не удалось открыть смету. Попробуйте ещё раз.",
    estimateEditTitle: "Редактировать смету",
    sendEstimate: "Отправить смету",
    estimateTitle: "Создать смету",
    estimateItems: "Позиции услуг",
    addItem: "+ Добавить позицию",
    itemDesc: "Описание",
    itemCat: "Категория",
    itemQty: "Кол-во",
    itemPrice: "Цена ($)",
    estimateNotes: "Заметки (необязательно)",
    estimateNotesPlaceholder: "Дополнительные заметки для клиента...",
    estimateSend: "Отправить клиенту",
    estimateSending: "Отправляем...",
    estimateSuccess: "Смета отправлена!",
    estimateErr: "Ошибка отправки сметы",
    noTax: "Без налога (скидка)",
    estimateSubtotal: "Подытог",
    estimateTaxLine: "Налог (8.25%)",
    estimateTotalLine: "Итого",
    fromPricebook: "Из прайс-листа",
    customItem: "Своё",
    partsCost: "Стоимость запчастей (факт., для отчётов $)",
    partsCostHint: "Только для внутреннего учёта — клиент не видит",
    searchJobs: "Поиск: имя, телефон, дата, адрес…",
    searchClear: "Сбросить",
    tabActive: "Активные",
    archiveJob: "В архив",
    restore: "Восстановить",
    archived: "Архив",
    noArchived: "Архив пуст",
    archiving: "Архивирование...",
    restoring: "Восстановление...",
    sendReview: "⭐ Запросить отзыв",
    sendReviewWa: "WhatsApp",
    sendingReview: "Отправляем...",
    reviewSent: "Ссылка на отзыв отправлена!",
    notifyMethod: "Отправить ссылку на оплату через",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Оба",
    clientContact: "Контакты клиента",
    noContactInfo: "Контактных данных нет",
    noNotificationWillBeSent: "уведомление не будет отправлено",
    statsClosed: "Всего закрыто",
    statsRevenue: "Общая выручка",
    statsMonth: "Этот месяц",
    statsMonthRev: "Этот месяц $",
    statsWeek: "Эта неделя",
    statsWeekJobs: "заказов за неделю",
    statsWeekLabor: "Работа",
    statsWeekParts: "Запчасти",
    statsWeekTax: "Налог (8.25%)",
    statsWeekNet: "Ваша доля",
    statsJobs: "заказов",
    statsTab: "Статистика",
    faceIdFailed: "Face ID не прошёл. Введите пароль.",
    faceIdRegFailed: "Не удалось включить Face ID",
    fidEnableTitle: "Включить Face ID?",
    fidEnableDesc: "Вход одним касанием без пароля.\nВаше лицо / отпечаток не покидает устройство.",
    fidEnable: "Включить Face ID / Fingerprint",
    fidRegistering: "Регистрация...",
    fidSkip: "Пропустить",
    fidSignIn: "Войти через Face ID",
    fidChecking: "Проверка...",
    fidUsePassword: "Войти по паролю",
    photosBtn: "📷 Фото",
    photoModal: "Фото заказа",
    photoAdd: "Сделать фото",
    photoGallery: "Выбрать из галереи (до 10 фото)",
    photoLoading: "Загрузка...",
    photoNone: "Фото нет",
    photoDelete: "Удалить",
    photoUploadFail: "Ошибка загрузки",
    sigTitle: "Подпись клиента",
    sigClear: "Очистить",
    sigDraw: "Нарисуйте подпись (опционально)",
    sigConsentText: "Подписывая, клиент разрешает HTR Dental выполнить описанный ремонт. Электронная подпись действительна по законодательству Техаса (TUETA).",
    sigOptional: "(опционально)",
    editEmail: "Изменить Email",
    emailSaved: "Email сохранён",
    emailSaveErr: "Ошибка сохранения Email",
    addEmail: "Добавить Email",
  },
  es: {
    title: "Portal del empleado",
    phone: "Teléfono",
    pin: "PIN",
    signIn: "Iniciar sesión",
    signingIn: "Iniciando sesión...",
    invalidLogin: "Teléfono o PIN inválido",
    connError: "Error de conexión",
    hello: "Hola,",
    logout: "Cerrar sesión",
    myJobs: "Mis trabajos",
    payroll: "Nómina",
    profile: "Perfil",
    refresh: "Actualizar",
    noJobs: "Aún no hay trabajos asignados",
    completed: "Completado",
    pending: "Pendiente",
    confirmed: "Confirmado",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Hecho",
    paid: "Pagado",
    cancelled: "Cancelado",
    period: "Período",
    jobsCount: "Trabajos",
    gross: "Bruto",
    deductions: "Deducciones",
    net: "Neto",
    noPayroll: "Aún no hay registros de nómina",
    car: "Coche",
    plate: "Placa",
    closeJob: "Cerrar trabajo",
    downloadReceipt: "Descargar recibo",
    generating: "Generando...",
    repairAmount: "Monto de reparación ($)",
    workPerformed: "Trabajo realizado",
    workPlaceholder: "Describe lo que se hizo...",
    partsReplaced: "Piezas reemplazadas",
    addPart: "+ Añadir pieza",
    paymentMethod: "Método de pago",
    cash: "Efectivo",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Abrir Stripe Dashboard",
    tapToPayInstruction: "Abre la app Stripe Dashboard → crea un pago → acerca la tarjeta del cliente",
    zelleInfo: "Enviar a: htrgroupllc@gmail.com",
    openPaymentLink: "Abrir enlace de pago",
    online: "En línea (Stripe)",
    clientReceiptLang: "Idioma del recibo del cliente",
    cancel: "Cancelar",
    submit: "Enviar",
    repairAmountReq: "El monto de la reparación es obligatorio",
    workPerformedReq: "El trabajo realizado es obligatorio",
    errorClosing: "Error al cerrar el trabajo",
    address: "Dirección",
    appliance: "Equipo dental",
    brandModel: "Marca/Modelo",
    date: "Fecha",
    time: "Hora",
    notes: "Notas",
    call: "Llamar",
    smsAction: "SMS",
    emailAction: "Email",
    navigate: "Navegar",
    receiptError: "No se pudo generar el recibo. Por favor, inténtelo de nuevo.",
    noProfile: "Cargando perfil...",
    estimateSent: "Presupuesto enviado",
    estimateEdit: "Editar y reenviar",
    estimateView: "Ver",
    estimateDownload: "PDF",
    estimateViewError: "No se pudo abrir el presupuesto. Inténtelo de nuevo.",
    estimateEditTitle: "Editar presupuesto",
    sendEstimate: "Enviar presupuesto",
    estimateTitle: "Crear presupuesto",
    estimateItems: "Servicios",
    addItem: "+ Agregar elemento",
    itemDesc: "Descripción",
    itemCat: "Categoría",
    itemQty: "Cant.",
    itemPrice: "Precio ($)",
    estimateNotes: "Notas (opcional)",
    estimateNotesPlaceholder: "Notas adicionales para el cliente...",
    estimateSend: "Enviar al cliente",
    estimateSending: "Enviando...",
    estimateSuccess: "¡Presupuesto enviado!",
    estimateErr: "Error al enviar presupuesto",
    noTax: "Sin impuesto (descuento)",
    estimateSubtotal: "Subtotal",
    estimateTaxLine: "Impuesto (8.25%)",
    estimateTotalLine: "Total",
    fromPricebook: "Del catálogo",
    customItem: "Personalizado",
    partsCost: "Costo de partes (real, para reportes $)",
    partsCostHint: "Solo interno — el cliente no lo ve",
    searchJobs: "Buscar: nombre, teléfono, fecha, dirección…",
    searchClear: "Limpiar",
    tabActive: "Activos",
    archiveJob: "Archivar",
    restore: "Restaurar",
    archived: "Archivados",
    noArchived: "No hay trabajos archivados",
    archiving: "Archivando...",
    restoring: "Restaurando...",
    sendReview: "⭐ Pedir reseña",
    sendReviewWa: "WhatsApp",
    sendingReview: "Enviando...",
    reviewSent: "¡Enlace de reseña enviado!",
    notifyMethod: "Enviar enlace de pago por",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Ambos",
    clientContact: "Contacto del cliente",
    noContactInfo: "Sin información de contacto",
    noNotificationWillBeSent: "no se enviará notificación",
    statsClosed: "Total cerrado",
    statsRevenue: "Ingresos totales",
    statsMonth: "Este mes",
    statsMonthRev: "Este mes $",
    statsWeek: "Esta semana",
    statsWeekJobs: "trabajos esta semana",
    statsWeekLabor: "Mano de obra",
    statsWeekParts: "Refacciones",
    statsWeekTax: "Impuesto (8.25%)",
    statsWeekNet: "Tu parte neta",
    statsJobs: "trabajos",
    statsTab: "Estadísticas",
    faceIdFailed: "Face ID fallido. Ingrese contraseña.",
    faceIdRegFailed: "No se pudo activar Face ID",
    fidEnableTitle: "¿Activar Face ID?",
    fidEnableDesc: "Ingrese con un toque, sin contraseña.\nSu cara / huella nunca sale del dispositivo.",
    fidEnable: "Activar Face ID / Huella",
    fidRegistering: "Registrando...",
    fidSkip: "Omitir",
    fidSignIn: "Entrar con Face ID",
    fidChecking: "Verificando...",
    fidUsePassword: "Entrar con contraseña",
    photosBtn: "📷 Fotos",
    photoModal: "Fotos del trabajo",
    photoAdd: "Tomar foto",
    photoGallery: "Elegir de galería (hasta 10)",
    photoLoading: "Cargando...",
    photoNone: "Sin fotos aún",
    photoDelete: "Eliminar",
    photoUploadFail: "Error al subir",
    sigTitle: "Firma del cliente",
    sigClear: "Limpiar",
    sigDraw: "Firme aquí (opcional)",
    sigConsentText: "Al firmar, el cliente autoriza a HTR Dental a realizar las reparaciones descritas. Firma electrónica válida bajo la ley de Texas (TUETA).",
    sigOptional: "(opcional)",
    editEmail: "Editar Email",
    emailSaved: "Email guardado",
    emailSaveErr: "Error al guardar email",
    addEmail: "Agregar Email",
  },
  tr: {
    title: "Personel Portalı",
    phone: "Telefon",
    pin: "PIN",
    signIn: "Giriş Yap",
    signingIn: "Giriş yapılıyor...",
    invalidLogin: "Geçersiz telefon veya PIN",
    connError: "Bağlantı hatası",
    hello: "Merhaba,",
    logout: "Çıkış Yap",
    myJobs: "İşlerim",
    payroll: "Maaş",
    profile: "Profil",
    refresh: "Yenile",
    noJobs: "Henüz atanmış iş yok",
    completed: "Tamamlandı",
    pending: "Beklemede",
    confirmed: "Onaylandı",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Bitti",
    paid: "Ödendi",
    cancelled: "İptal edildi",
    period: "Dönem",
    jobsCount: "İş sayısı",
    gross: "Brüt",
    deductions: "Kesintiler",
    net: "Net",
    noPayroll: "Henüz maaş kaydı yok",
    car: "Araç",
    plate: "Plaka",
    closeJob: "İşi Kapat",
    downloadReceipt: "Fişi İndir",
    generating: "Oluşturuluyor...",
    repairAmount: "Onarım Tutarı ($)",
    workPerformed: "Yapılan İş",
    workPlaceholder: "Ne yapıldığını açıklayın...",
    partsReplaced: "Değişen Parçalar",
    addPart: "+ Parça Ekle",
    paymentMethod: "Ödeme Yöntemi",
    cash: "Nakit",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Stripe Dashboard'u Aç",
    tapToPayInstruction: "Stripe Dashboard uygulamasını aç → ödeme oluştur → müşteri kartını yaklaştır",
    zelleInfo: "Gönder: htrgroupllc@gmail.com",
    openPaymentLink: "Ödeme Linkini Aç",
    online: "Çevrimiçi (Stripe)",
    clientReceiptLang: "Müşteri Fiş Dili",
    cancel: "İptal",
    submit: "Gönder",
    repairAmountReq: "Onarım tutarı gerekli",
    workPerformedReq: "Yapılan iş gerekli",
    errorClosing: "İş kapatılırken hata oluştu",
    address: "Adres",
    appliance: "Cihaz",
    brandModel: "Marka/Model",
    date: "Tarih",
    time: "Saat",
    notes: "Notlar",
    call: "Ara",
    navigate: "Yol Tarifi",
    receiptError: "Fiş oluşturulamadı. Lütfen tekrar deneyin.",
    noProfile: "Profil yükleniyor...",
    sendEstimate: "Teklif Gönder",
    estimateTitle: "Teklif Oluştur",
    estimateItems: "Hizmet Kalemleri",
    addItem: "+ Kalem Ekle",
    itemDesc: "Açıklama",
    itemCat: "Kategori",
    itemQty: "Adet",
    itemPrice: "Fiyat ($)",
    estimateNotes: "Notlar (isteğe bağlı)",
    estimateNotesPlaceholder: "Müşteri için ek notlar...",
    estimateSend: "Müşteriye Gönder",
    estimateSending: "Gönderiliyor...",
    estimateSuccess: "Teklif gönderildi!",
    estimateErr: "Teklif gönderme hatası",
    noTax: "Vergisiz (indirim)",
    estimateSubtotal: "Ara toplam",
    estimateTaxLine: "Vergi (8.25%)",
    estimateTotalLine: "Toplam",
    fromPricebook: "Fiyat listesinden",
    customItem: "Özel",
    partsCost: "Parça maliyeti (gerçek, raporlar için $)",
    partsCostHint: "Yalnızca dahili — müşteri görmez",
    searchJobs: "Ara: ad, telefon, tarih, adres…",
    searchClear: "Temizle",
    tabActive: "Aktif",
    archiveJob: "Arşivle",
    restore: "Geri Yükle",
    archived: "Arşiv",
    noArchived: "Arşivlenmiş iş yok",
    archiving: "Arşivleniyor...",
    restoring: "Geri yükleniyor...",
    sendReview: "⭐ Yorum İste",
    sendReviewWa: "WhatsApp",
    sendingReview: "Gönderiliyor...",
    reviewSent: "Yorum bağlantısı gönderildi!",
    notifyMethod: "Ödeme bağlantısını gönder",
    viaEmail: "E-posta",
    viaSMS: "SMS",
    viaBoth: "İkisi de",
    clientContact: "Müşteri iletişim bilgisi",
    noContactInfo: "İletişim bilgisi yok",
    noNotificationWillBeSent: "bildirim gönderilmeyecek",
    statsClosed: "Toplam Kapatılan",
    statsRevenue: "Toplam Gelir",
    statsMonth: "Bu Ay",
    statsMonthRev: "Bu Ay $",
    statsWeek: "Bu Hafta",
    statsWeekJobs: "bu haftaki iş",
    statsWeekLabor: "İşçilik",
    statsWeekParts: "Parçalar",
    statsWeekTax: "Vergi (8.25%)",
    statsWeekNet: "Net payınız",
    statsJobs: "iş",
    statsTab: "İstatistik",
    faceIdFailed: "Face ID başarısız. Şifre girin.",
    faceIdRegFailed: "Face ID etkinleştirilemedi",
    fidEnableTitle: "Face ID etkinleştirilsin mi?",
    fidEnableDesc: "Şifresiz tek dokunuşla giriş yapın.\nYüzünüz / parmak iziniz cihazdan çıkmaz.",
    fidEnable: "Face ID / Parmak İzi Etkinleştir",
    fidRegistering: "Kaydediliyor...",
    fidSkip: "Atla",
    fidSignIn: "Face ID ile Giriş",
    fidChecking: "Kontrol ediliyor...",
    fidUsePassword: "Şifre ile giriş",
    photosBtn: "📷 Fotoğraflar",
    photoModal: "İş Fotoğrafları",
    photoAdd: "Fotoğraf Çek",
    photoGallery: "Galeriden Seç (10'a kadar)",
    photoLoading: "Yükleniyor...",
    photoNone: "Henüz fotoğraf yok",
    photoDelete: "Sil",
    photoUploadFail: "Yükleme hatası",
    sigTitle: "Müşteri İmzası",
    sigClear: "Temizle",
    sigDraw: "Buraya imzalayın (isteğe bağlı)",
    sigConsentText: "İmzalayarak müşteri, HTR Dental'in açıklanan onarımları yapmasını onaylar. Texas hukukuna göre geçerli elektronik imza (TUETA).",
    sigOptional: "(isteğe bağlı)",
    editEmail: "E-posta Düzenle",
    emailSaved: "E-posta kaydedildi",
    emailSaveErr: "E-posta kaydetme hatası",
    addEmail: "E-posta Ekle",
  },
  az: {
    title: "İşçi Portalı",
    phone: "Telefon",
    pin: "PIN",
    signIn: "Daxil ol",
    signingIn: "Daxil olunur...",
    invalidLogin: "Yanlış telefon və ya PIN",
    connError: "Bağlantı xətası",
    hello: "Salam,",
    logout: "Çıxış",
    myJobs: "İşlərim",
    calendarTab: "Cədvəl",
    calTitle: "Cədvəlim",
    calWeek: "Həftə",
    calMonth: "Ay",
    calYear: "İl",
    calToday: "Bu gün",
    calAllEmployees: "Hamısı",
    calNoEvents: "Bu dövrdə iş yoxdur",
    calLoading: "Yüklənir…",
    calDragHint: "İşi təqvimdə başqa günün üzərinə sürükləyin",
    calSerial: "Seriya №",
    calTechnician: "Texnik",
    calOverdue: "Gecikmiş",
    calRescheduleOk: "Cədvəl yeniləndi",
    calRescheduleErr: "Köçürülmə alınmadı",
    calStatusCompleted: "Tamamlandı",
    calStatusApproved: "Təsdiqləndi",
    calStatusPending: "Gözləyir",
    calBizAll: "Hamısı",
    calBizAppliance: "Appliance",
    calBizDental: "Dental",
    calTapHint: "Günə toxunun — işi başqa günə sürükləyin",
    calMoveJob: "Köçür",
    calPickTime: "Vaxt seçin",
    calOpenCrm: "İşi aç",
    calBackToCalendar: "Cədvələ qayıt",
    payroll: "Maaş",
    profile: "Profil",
    refresh: "Yenilə",
    noJobs: "Hələ təyin olunmuş iş yoxdur",
    completed: "Tamamlandı",
    pending: "Gözləyir",
    confirmed: "Təsdiqləndi",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Hazırdır",
    paid: "Ödənildi",
    cancelled: "Ləğv edildi",
    period: "Dövr",
    jobsCount: "İşlər",
    gross: "Ümumi",
    deductions: "Tutulmalar",
    net: "Xalis",
    noPayroll: "Hələ maaş qeydi yoxdur",
    car: "Maşın",
    plate: "Nömrə",
    closeJob: "İşi Bağla",
    downloadReceipt: "Qəbzi Yüklə",
    generating: "Hazırlanır...",
    repairAmount: "Təmir Məbləği ($)",
    workPerformed: "Görülən İş",
    workPlaceholder: "Nə edildiyini təsvir edin...",
    partsReplaced: "Dəyişdirilmiş Hissələr",
    addPart: "+ Hissə Əlavə Et",
    paymentMethod: "Ödəniş Üsulu",
    cash: "Nağd",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Stripe Dashboard Aç",
    tapToPayInstruction: "Stripe Dashboard tətbiqini açın → ödəniş yaradın → müştəri kartını yaxınlaşdırın",
    zelleInfo: "Göndər: htrgroupllc@gmail.com",
    openPaymentLink: "Ödəniş Linkini Aç",
    online: "Onlayn (Stripe)",
    clientReceiptLang: "Müştəri Qəbz Dili",
    cancel: "Ləğv et",
    submit: "Göndər",
    repairAmountReq: "Təmir məbləği tələb olunur",
    workPerformedReq: "Görülən iş tələb olunur",
    errorClosing: "İşi bağlayarkən xəta",
    address: "Ünvan",
    appliance: "Avadanlıq",
    brandModel: "Marka/Model",
    date: "Tarix",
    time: "Saat",
    notes: "Qeydlər",
    call: "Zəng et",
    smsAction: "SMS",
    emailAction: "E-poçt",
    navigate: "Naviqasiya",
    receiptError: "Qəbz hazırlana bilmədi. Yenidən cəhd edin.",
    noProfile: "Profil yüklənir...",
    estimateSent: "Smeta göndərildi",
    estimateEdit: "Düzəlt və yenidən göndər",
    estimateView: "Bax",
    estimateDownload: "PDF",
    estimateViewError: "Smeta açıla bilmədi. Yenidən cəhd edin.",
    estimateEditTitle: "Smetanı redaktə et",
    sendEstimate: "Smeta Göndər",
    estimateTitle: "Smeta Yarat",
    estimateItems: "Xidmət Maddələri",
    addItem: "+ Maddə Əlavə Et",
    itemDesc: "Təsvir",
    itemCat: "Kateqoriya",
    itemQty: "Say",
    itemPrice: "Qiymət ($)",
    estimateNotes: "Qeydlər (isteğe bağlı)",
    estimateNotesPlaceholder: "Müştəri üçün əlavə qeydlər...",
    estimateSend: "Müştəriyə Göndər",
    estimateSending: "Göndərilir...",
    estimateSuccess: "Smeta göndərildi!",
    estimateErr: "Smeta göndərmə xətası",
    noTax: "Vergisiz (endirim)",
    estimateSubtotal: "Aralıq cəm",
    estimateTaxLine: "Vergi (8.25%)",
    estimateTotalLine: "Cəmi",
    fromPricebook: "Qiymət siyahısından",
    customItem: "Xüsusi",
    partsCost: "Hissə dəyəri (faktiki, hesabatlar üçün $)",
    partsCostHint: "Yalnız daxili — müştəri görmür",
    searchJobs: "Axtar: ad, telefon, tarix, ünvan…",
    searchClear: "Təmizlə",
    tabActive: "Aktiv",
    archiveJob: "Arxivlə",
    restore: "Bərpa et",
    archived: "Arxiv",
    noArchived: "Arxivlənmiş iş yoxdur",
    archiving: "Arxivlənir...",
    restoring: "Bərpa edilir...",
    sendReview: "⭐ Rəy İstə",
    sendReviewWa: "WhatsApp",
    sendingReview: "Göndərilir...",
    reviewSent: "Rəy linki göndərildi!",
    notifyMethod: "Ödəniş linkini göndər",
    viaEmail: "E-poçt",
    viaSMS: "SMS",
    viaBoth: "Hər ikisi",
    clientContact: "Müştəri əlaqəsi",
    noContactInfo: "Əlaqə məlumatı yoxdur",
    noNotificationWillBeSent: "bildiriş göndərilməyəcək",
    statsClosed: "Cəmi Bağlandı",
    statsRevenue: "Ümumi Gəlir",
    statsMonth: "Bu Ay",
    statsMonthRev: "Bu Ay $",
    statsWeek: "Bu Həftə",
    statsWeekJobs: "bu həftəki iş",
    statsWeekLabor: "Əmək",
    statsWeekParts: "Hissələr",
    statsWeekTax: "Vergi (8.25%)",
    statsWeekNet: "Sizin payınız",
    statsJobs: "iş",
    statsTab: "Statistika",
    faceIdFailed: "Face ID uğursuz oldu. Şifrəni daxil edin.",
    faceIdRegFailed: "Face ID aktiv edilə bilmədi",
    fidEnableTitle: "Face ID aktiv edilsin?",
    fidEnableDesc: "Şifrəsiz bir toxunuşla daxil olun.\nÜzünüz / barmaq iziniz cihazdan çıxmır.",
    fidEnable: "Face ID / Barmaq İzi Aktiv Et",
    fidRegistering: "Qeyd edilir...",
    fidSkip: "Keç",
    fidSignIn: "Face ID ilə Daxil Ol",
    fidChecking: "Yoxlanılır...",
    fidUsePassword: "Şifrə ilə daxil ol",
    photosBtn: "📷 Şəkillər",
    photoModal: "İş Şəkilləri",
    photoAdd: "Şəkil çək",
    photoGallery: "Qalereyadan seç (10-a qədər)",
    photoLoading: "Yüklənir...",
    photoNone: "Hələ şəkil yoxdur",
    photoDelete: "Sil",
    photoUploadFail: "Yükləmə xətası",
    sigTitle: "Müştəri İmzası",
    sigClear: "Təmizlə",
    sigDraw: "Buraya imzalayın (ixtiyari)",
    sigConsentText: "İmzalayaraq müştəri HTR Dental-in təsvir olunan təmirləri etməsinə icazə verir. Texas qanunvericiliyinə əsasən etibarlı elektron imza (TUETA).",
    sigOptional: "(ixtiyari)",
    editEmail: "E-poçtu Yenilə",
    emailSaved: "E-poçt qeydə alındı",
    emailSaveErr: "E-poçt saxlama xətası",
    addEmail: "E-poçt Əlavə Et",
  },
  uk: {
    title: "Портал працівника",
    phone: "Телефон",
    pin: "ПІН-код",
    signIn: "Увійти",
    signingIn: "Вхід...",
    invalidLogin: "Невірний телефон або ПІН",
    connError: "Помилка з'єднання",
    hello: "Привіт,",
    logout: "Вийти",
    myJobs: "Мої роботи",
    payroll: "Зарплата",
    profile: "Профіль",
    refresh: "Оновити",
    noJobs: "Призначених робіт поки немає",
    completed: "Завершено",
    pending: "Очікує",
    confirmed: "Підтверджено",
    bizAppliance: "Appliance",
    bizDental: "Dental",
    done: "Готово",
    paid: "Оплачено",
    cancelled: "Скасовано",
    period: "Період",
    jobsCount: "Робіт",
    gross: "Разом",
    deductions: "Відрахування",
    net: "До виплати",
    noPayroll: "Записів про зарплату поки немає",
    car: "Авто",
    plate: "Номер",
    closeJob: "Закрити роботу",
    downloadReceipt: "Завантажити чек",
    generating: "Створення...",
    repairAmount: "Сума ремонту ($)",
    workPerformed: "Виконана робота",
    workPlaceholder: "Опишіть, що було зроблено...",
    partsReplaced: "Замінені деталі",
    addPart: "+ Додати деталь",
    paymentMethod: "Спосіб оплати",
    cash: "Готівка",
    zelle: "Zelle",
    tapToPay: "Tap to Pay",
    openStripeApp: "Відкрити Stripe Dashboard",
    tapToPayInstruction: "Відкрийте Stripe Dashboard → створіть платіж → піднесіть картку клієнта",
    zelleInfo: "Надіслати: htrgroupllc@gmail.com",
    openPaymentLink: "Відкрити посилання оплати",
    online: "Онлайн (Stripe)",
    clientReceiptLang: "Мова чека клієнта",
    cancel: "Скасувати",
    submit: "Надіслати",
    repairAmountReq: "Сума ремонту обов'язкова",
    workPerformedReq: "Опис роботи обов'язковий",
    errorClosing: "Помилка при закритті роботи",
    address: "Адреса",
    appliance: "Техніка",
    brandModel: "Марка/Модель",
    date: "Дата",
    time: "Час",
    notes: "Примітки",
    call: "Зателефонувати",
    navigate: "Маршрут",
    receiptError: "Не вдалося створити чек. Спробуйте ще раз.",
    noProfile: "Завантаження профілю...",
    sendEstimate: "Надіслати кошторис",
    estimateTitle: "Створити кошторис",
    estimateItems: "Послуги",
    addItem: "+ Додати позицію",
    itemDesc: "Опис",
    itemCat: "Категорія",
    itemQty: "К-сть",
    itemPrice: "Ціна ($)",
    estimateNotes: "Нотатки (необов'язково)",
    estimateNotesPlaceholder: "Додаткові нотатки для клієнта...",
    estimateSend: "Надіслати клієнту",
    estimateSending: "Надсилаємо...",
    estimateSuccess: "Кошторис надіслано!",
    estimateErr: "Помилка надсилання кошторису",
    noTax: "Без податку (знижка)",
    estimateSubtotal: "Підсумок",
    estimateTaxLine: "Податок (8.25%)",
    estimateTotalLine: "Разом",
    fromPricebook: "З прайс-листа",
    customItem: "Своє",
    partsCost: "Вартість деталей (факт., для звітів $)",
    partsCostHint: "Лише для внутрішнього обліку — клієнт не бачить",
    searchJobs: "Пошук: ім'я, телефон, дата, адреса…",
    searchClear: "Скинути",
    tabActive: "Активні",
    archiveJob: "В архів",
    restore: "Відновити",
    archived: "Архів",
    noArchived: "Архів порожній",
    archiving: "Архівування...",
    restoring: "Відновлення...",
    sendReview: "⭐ Запросити відгук",
    sendReviewWa: "WhatsApp",
    sendingReview: "Надсилаємо...",
    reviewSent: "Посилання на відгук надіслано!",
    notifyMethod: "Надіслати посилання на оплату через",
    viaEmail: "Email",
    viaSMS: "SMS",
    viaBoth: "Обидва",
    clientContact: "Контакти клієнта",
    noContactInfo: "Контактних даних немає",
    noNotificationWillBeSent: "повідомлення не буде надіслано",
    statsClosed: "Всього закрито",
    statsRevenue: "Загальна виручка",
    statsMonth: "Цей місяць",
    statsMonthRev: "Цей місяць $",
    statsWeek: "Цей тиждень",
    statsWeekJobs: "робіт за тиждень",
    statsWeekLabor: "Робота",
    statsWeekParts: "Запчастини",
    statsWeekTax: "Податок (8.25%)",
    statsWeekNet: "Ваша частка",
    statsJobs: "робіт",
    statsTab: "Статистика",
    faceIdFailed: "Face ID не пройшов. Введіть пароль.",
    faceIdRegFailed: "Не вдалося увімкнути Face ID",
    fidEnableTitle: "Увімкнути Face ID?",
    fidEnableDesc: "Вхід одним дотиком без пароля.\nВаше обличчя / відбиток не залишає пристрій.",
    fidEnable: "Увімкнути Face ID / Відбиток",
    fidRegistering: "Реєстрація...",
    fidSkip: "Пропустити",
    fidSignIn: "Увійти через Face ID",
    fidChecking: "Перевірка...",
    fidUsePassword: "Увійти за паролем",
    photosBtn: "📷 Фото",
    photoModal: "Фото замовлення",
    photoAdd: "Зробити фото",
    photoGallery: "Обрати з галереї (до 10 фото)",
    photoLoading: "Завантаження...",
    photoNone: "Фото відсутні",
    photoDelete: "Видалити",
    photoUploadFail: "Помилка завантаження",
    sigTitle: "Підпис клієнта",
    sigClear: "Очистити",
    sigDraw: "Намалюйте підпис (опціонально)",
    sigConsentText: "Підписуючи, клієнт дозволяє HTR Dental виконати описаний ремонт. Електронний підпис дійсний за законодавством Техасу (TUETA).",
    sigOptional: "(опціонально)",
    editEmail: "Оновити Email",
    emailSaved: "Email збережено",
    emailSaveErr: "Помилка збереження Email",
    addEmail: "Додати Email",
  },
};

interface EmpLangContextType {
  lang: EmpLang;
  setLang: (lang: EmpLang) => void;
  t: (key: string) => string;
}

const EmpLangContext = createContext<EmpLangContextType | undefined>(undefined);

export function EmpLangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<EmpLang>(() => {
    const saved = localStorage.getItem("empUiLang");
    return (saved as EmpLang) || "en";
  });

  const setLang = useCallback((newLang: EmpLang) => {
    setLangState(newLang);
    localStorage.setItem("empUiLang", newLang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang][key] || key;
  }, [lang]);

  return (
    <EmpLangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </EmpLangContext.Provider>
  );
}

export function useEmpLang() {
  const context = useContext(EmpLangContext);
  if (!context) throw new Error("useEmpLang must be used within EmpLangProvider");
  return context;
}
